### ISSUE TITLE
Airlines.db update

### ISSUE THREAD

**Issue by ssthomassen** [greatscottgadgets/hackrf#1002]
Hi,

I want to know how I can update the Airlines.db file? Cant find any documentation for that file, but it looks kind of simple to update?

First alot of 3 letter 'words', and the the description, but do i have to write all down alphabetic?

**Comment by straithe** [comment]
I'm sorry. I don't know what Airlines.db is referring to. I've searched the HackRF code and can't find any reference to what you are talking about. Are you perhaps confusing the HackRF code with the [mayhem code](https://github.com/eried/portapack-mayhem)?

**Comment by ssthomassen** [comment]
Thanks for your answer @straithe , I thought the HackRF was the basic, and mayhem was a layer on top. But it can be that i should ask someone with mayhem knowledge. The Airlines.db is the list for the ADB-S view, to see airlines company.

**Comment by straithe** [comment]
I don't know much about Mayhem, so I don't have the skill to help you further. I suggest you ask your question on the Mayhem repository I linked in my last message.
