### ISSUE TITLE
NXP chip heats up considerably, whole thing doesn't work

### ISSUE THREAD

**Issue by cab404** [greatscottgadgets/hackrf#1005]
While I was using HackRF with PortaPack, it suddenly stopped working.
After I disassembled it for inspection, I've noticed worrying smell of burnt resistors, but didn't find any obvious culprit.

When I connect 5V, NXP chip starts to heat up a lot.

**Comment by straithe** [comment]
Can you please post a picture of your HackRF, not in the PortaPack, front and back?

**Comment by cab404** [comment]
![IMG_20211202_155432](https://user-images.githubusercontent.com/6453661/144426178-4d3d2706-3992-4ebf-826e-cda0ae1fdcec.jpg)
![IMG_20211202_155138](https://user-images.githubusercontent.com/6453661/144426193-12ac42ef-1d0c-4915-b343-3d6f16e069b4.jpg)

**Comment by straithe** [comment]
Thank you for the pictures! Unfortunately this appears to be a clone. We have no recourse to help you get a replacement, but you can contact the supplier that you purchased it from and see if they can help you.

**Comment by cab404** [comment]
> Thank you for the pictures! Unfortunately this appears to be a clone. We have no recourse to help you get a replacement, but you can contact the supplier that you purchased it from and see if they can help you.

Oh, okay, thank you nonetheless!

**Comment by straithe** [comment]
Good luck!
