### ISSUE TITLE
hackrf updated firmware not working properly

### ISSUE THREAD

**Issue by EhtishamSabir** [greatscottgadgets/hackrf#1030]
How do I get hackrf 2014.08.1 binary? cause after updating firmware my hackrf is not capturing my car key frequency that's strange... I tried all firmware with binaries...

Here is my current info 
hackrf_info version: git-bf84a3a
libhackrf version: git-bf84a3a (0.6)
Found HackRF
Index: 0
Serial number: 0000000000000000044c63c83647421b
Board ID Number: 2 (HackRF One)
Firmware Version: 2017.02.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x00584f58
![image](https://user-images.githubusercontent.com/36196667/148507520-fe3e2ad7-6b75-4016-9042-389fb3ba8ea0.png)

**Comment by gozu42** [comment]
since you are running bf84a3a on the host side, which is a very-late-2021 not-release version...
... please update the firmware also to bf84a3a or at least 2021.03.1.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
