### ISSUE TITLE
Problem with HackRF and RationalWaves

### ISSUE THREAD

**Issue by jaeger-audiodesign** [greatscottgadgets/hackrf#1032]
My HackRF works under Win10 with SDR-Console on my MacBook with Parallels and on my ThinkPad.
I installed the app Rational Waves on both devices. The App detects the HackRF on both devices the RX LED light up when I start scanning but I get no data. Has anyone an idea?

On my HackRF is the actual firmware installed.

**Comment by straithe** [comment]
I don't quite understand what question you are asking, so I have some clarifying questions. Is there a particular reason you are using Rational Waves? Are you specifically asking for help with Rational Waves, or are you asking a question about your HackRF? Any extra detail would be appreciated.

**Comment by jaeger-audiodesign** [comment]
The main problem was, that the HackRF didn't work under Windows10. No I found out, that this was an issue with the newest Firmware. I made a downgrade to the 2017 FW Version and now I get data in the hackRF_sweep app. I suspect that the RationalWaves software works on the basic of the hackRF_sweep tool. I wrote the support and wait for a feedback...

**Comment by straithe** [comment]
Which support did you write to?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
