### ISSUE TITLE
FIX ERROR RX

### ISSUE THREAD

**Issue by antbhlk** [greatscottgadgets/hackrf#1035]
### Steps to reproduce
1. 
1. 
1. 

### Expected behaviour
Tell us what you expect should happen

### Actual behaviour
Tell us what happens instead

### Version information
**Operating system**:

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
