### ISSUE TITLE
HackRf not working with digital radio but working well with Analog radio, please help to understand the issue,

### ISSUE THREAD

**Issue by ckdada1423** [greatscottgadgets/hackrf#1037]

**Comment by straithe** [comment]
This is not enough detail to help you. Can you please add more detail about what methods you are trying and what your goal is?

**Comment by ckdada1423** [comment]
Yes, sure. I am using the software gnuradio. When i am sending analog signal from the gnu radio then hackrf show me the frequency single but when i am sending the digital signal form the gnuradio then hackrf unable to find the frequency.

**Comment by straithe** [comment]
Can you please post a picture of your flow graph?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
