### ISSUE TITLE
HackRF One only 3v3 Light 

### ISSUE THREAD

**Issue by 0xGSMonkey** [greatscottgadgets/hackrf#1038]
### Steps to reproduce
1.  Connected Pin 11 and Pin 18 on P22
1. Disconnect Pin 11 and Pin 18 on P22
1. 

### Expected behaviour
Only the 3v3 Light is on and sometimes the RF light.

### Actual behaviour
I don't think it is the USB cable I have used 4 different USB cables and all of them show the 3V3 light as being the only light that shows. I am not sure what happened. I connected PIn 11 and PIn 18 on Expansion Interface 22 without reading the docs. Did this fry my hackrf one? D:

**Comment by gozu42** [comment]
shorting VCC to GND seems like a good way to fry things, yes.
can you measure the voltage between pins 11+18 on P22?

and if i may ask, why did you connect these pins to begin with? (as in, what were you trying to do?)
and just to add the standard request: can you please post pics of the front+back of your hackrf board?

**Comment by 0xGSMonkey** [comment]
I added pins to the operacake in order to use it as an add-on board I think those two pins connected on the operacake board and possibly fried the hackrf one. 

Between Pin 11 and Pin 18 on P22 the volage is 3.25. Is there a datasheet or something on what it should be? I did a visual inspection of the board and there doesn't seem to be any damage, but here is a picture of the board. 

It still only seems to show that the 3v3 light is the only light that comes on. 

<a href="https://ibb.co/QXvwyds"><img src="https://i.ibb.co/M9k0F6q/545-FADD1-8-E43-4-CC6-9-F88-7-E274769-DF94.jpg" alt="545-FADD1-8-E43-4-CC6-9-F88-7-E274769-DF94" border="0"></a>
<a href="https://ibb.co/6X9MbXG"><img src="https://i.ibb.co/HhwSYhR/4-C9-DEDEE-4316-4-DCF-ADAE-7-B728-ED325-BA.jpg" alt="4-C9-DEDEE-4316-4-DCF-ADAE-7-B728-ED325-BA" border="0"></a><br />

**Comment by straithe** [comment]
Are you able to bring up the HackRF with DFU mode?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
