### ISSUE TITLE
hackrf one : hackrf_info version: git-e93d70e , libhackrf version: unknown (0.5)

### ISSUE THREAD

**Issue by KimlongSeng** [greatscottgadgets/hackrf#1054]
# Is this am issue?

Hackrf can't recognize it version 

hackrf_info version: git-e93d70e
libhackrf version: unknown (0.5)

### Steps to reproduce
1. run : $ sudo apt-get install hackrf
2. run : $ hackrf_info
3.

### Expected behaviour

*hackrf_info version: 2018.01.1-2 ?
*libhackrf version: 2018.01.1-2 ?
Found HackRF

### Actual behaviour

hackrf_info version: git-e93d70e
libhackrf version: unknown (0.5)
Found HackRF

### Version information
**Operating system**: Raspberry Pi 4 (Linux)

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.
GNU Radio Companion 3.7.14.0
### Output
```


```

**Comment by straithe** [comment]
I'm not quite certain what your concern is. Can you please provide more details?

**Comment by KimlongSeng** [comment]
hackrf_info version: git-e93d70e
libhackrf version: unknown (0.5)

I install the libhackrf, but it just reported as unknown. 

Thank you for taking the time to respond.

**Comment by straithe** [comment]
In many scenarios, having the libhackrf version be unknown is normal. As for your hackrf_info version being different, how did you install the HackRF software?

**Comment by KimlongSeng** [comment]
Just using 
$ sudo apt-get install hackrf

Like you said, the hackrf one is working fine with the version and libhackrf = unknown(0.5).

I was just curious.
