### ISSUE TITLE
hackRF one RF led red 

### ISSUE THREAD

**Issue by omurugur** [greatscottgadgets/hackrf#1055]
I have a hackrf one device in my hand and when I connect this device to the computer, I cannot receive broadcasts and the rf lamp is red and the 1v8 lamp is orange. I updated the firmware to the latest version but the problem did not go away. I plug in the pineapple antenna but I can't get any radio.

**Comment by straithe** [comment]
Can you please describe your set up, such as what software you are using, and how you are going about testing your HackRF?

**Comment by omurugur** [comment]
I updated to the latest version, I connected the pineapple antenna to my device. universal radio hacker , HDSDR ,gnu radio does not work on any of the installed windows. red led is on in the rf area

**Comment by miek** [comment]
Just to clarify: the colours of the LEDs don't mean anything, so a red LED being lit up doesn't mean that something is wrong. See the FAQ for more detail: https://hackrf.readthedocs.io/en/latest/faq.html#why-are-the-leds-on-hackrf-different-colours

**Comment by straithe** [comment]
@omurugur are you still having any concerns, or are you happy with the explanation of the LED colours?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
