### ISSUE TITLE
hackrf_transfer returns undefined symbol error

### ISSUE THREAD

**Issue by Jcwscience** [greatscottgadgets/hackrf#1064]
### Steps to reproduce
Run hackrf_transfer

### Expected behaviour
Transmit

### Actual behaviour
hackrf_transfer: symbol lookup error: hackrf_transfer: undefined symbol: hackrf_get_m0_state

### Version information
Ubuntu Impish aarch64

hackrf_info version: git-3344ea8
libhackrf version: unknown (0.5)
Found HackRF
Index: 0
Serial number: 0000000000000000f77c60dc275297c3
Board ID Number: 2 (HackRF One)
Firmware Version: 2021.03.1 (API:1.04)
Part ID Number: 0xa000cb3c 0x005d4366

**Comment by martinling** [comment]
`hackrf_get_m0_state` was just added to the library recently in #982. It looks like you're trying to run a new `hackrf_transfer` against an installed `libhackrf.so.0` that's not as up to date.

**Comment by Jcwscience** [comment]
Ok that makes sense, I’ll hunt down the library and remove it and rebuild the project. Thanks!

**Comment by Jcwscience** [comment]
@martinling That worked, I had a system installation still that I forgot about
