### ISSUE TITLE
Precision measure request

### ISSUE THREAD

**Issue by glaier** [greatscottgadgets/hackrf#1083]
The documentation for hackrf_sweep and other command-line tools for HackRF would benefit from the addition of precision measures to the output. Within each bin and for each measurement the precision is dependent on several things including instrument precision, which is again a variable dependent on several tuning factors. The addition of precision measures requires more theory to be explained in the documentation, bringing the electronics implementation and schematics closer to the software tools. 
Please consider my request. I believe it will be a very convenient development instrument with respect to both hardware and software.

**Comment by straithe** [comment]
I'm closing this issue based on conversation in https://github.com/greatscottgadgets/hackrf/issues/1078
