### ISSUE TITLE
Hackrf is getting HOT

### ISSUE THREAD

**Issue by catalinalb** [greatscottgadgets/hackrf#1089]
### Expected behaviour
Start Up

### Actual behaviour
LED´s turn on and the NXP big Chip is getting hot

### Version information
**Same on linux or windows**:

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```I did flahsed the mayhem v1.5.1 in order to finally get my cheap Portapack H2 board. It started and worked untill the next power off. After which the screen was again blank. Therefore I just keept starting and stopping the board while keeping the up, down or left buttons in order to select the proper driver. The battery was also connected along with the usb cable. 

After which I noticed that the board NXP´s chip is getting warm. I removed the portapack and connected the board again but is not recognized. I did entered the DFU mode but the chip is still getting hot. 
How can I flash it since is not recognized by windows or linux. I do hace an AVR Dragon board with JTAG .... 

Thank you

**Comment by straithe** [comment]
Can you please post a picture of the front and the back of your HackRF?

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
