### ISSUE TITLE
Poor Rx on VHF and below

### ISSUE THREAD

**Issue by tmadushan** [greatscottgadgets/hackrf#1093]
### Steps to reproduce
1. Tune in to 443.000MHz
2. Set LNA Gain = 8dB, VGA Gain = 32dB, AMP = OFF
3. Note the results
4. Tune in to 145.775MHz
5. Set LNA Gain = 8dB, VGA Gain = 32dB, AMP = OFF
6. Note the results
7. Set LNA Gain =32dB, VGA Gain = 46dB, AMP = ON
6.  Note the results

### Expected behaviour
I should see sharp, tall spikes on all the above occasions. 

### Actual behaviour
I see such spikes only on the 70cm UHF frequencies. 
But on the lower frequencies (FM Broadcast range, 144MHz, 138MHz etc.), there is almost no signal received. 

I replaced the U13 MGA81563 LNA to see if that is the culprit. But it seems not. The noise floor goes up when Amp is turned ON. 

### Version information
Using Windows 10, SDR Sharp 1.0.0.1732 

### Output

Screenshot of UHF rx. Works great. 
![443MHz](https://user-images.githubusercontent.com/14135458/164252417-6ea6e5dd-1124-462a-bcbd-73152b277ff9.png)

Screenshot of VHF rx. Amp OFF. 
![145775MHz](https://user-images.githubusercontent.com/14135458/164252618-f46d77e4-3919-4089-a003-73475f19a87b.png)

Screenshot of VHF rx. Amp ON. 
![145775-LNAMHz](https://user-images.githubusercontent.com/14135458/164252671-9bef6f01-c060-469c-9cb6-2ec69baec2a5.png)

Any thoughts on this, please? 
Thanks in advance, 
Tharanga-4S6TMP.

**Comment by straithe** [comment]
Can you tell me more about  why you expect tall spikes in all of the instances you've highlighted?

**Comment by straithe** [comment]
What antenna are you using?

**Comment by tmadushan** [comment]
For VHF - 138MHz QFH and a Quarter wave whip
For UHF -  Quarter wave whip

**Comment by tmadushan** [comment]
I am Txing using an HT with ~5W (both VHF & UHF). Distance between the HackRF & HT is unchanged,

**Comment by tmadushan** [comment]
My thoughts exactly. BTW I did not Tx for long, just PTT for a second and let go. 

My problem is why the reception is so poor on VHF but not UHF? I started replacing the antenna switches and RF Amps. I will keep this thread updated. 

Thank you @mossmann

**Comment by mossmann** [comment]
A tiny crack in a solder joint acts like a capacitor (in series) which is why it attenuates lower frequencies more than higher frequencies. There is a good chance that the break is undetectable above some even higher frequency like 2 GHz.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in the last thirty days, but please re-open this issue or open a new one if you still need assistance.
