### ISSUE TITLE
hackrf_sweep timestamp changes during sweep

### ISSUE THREAD

**Issue by audiocrush** [greatscottgadgets/hackrf#1098]
### Steps to reproduce
1. running hackrf_sweep appending output to csv

### Expected behaviour
Well I hoped that during a sweep the timestamp stays the same so that plotsweep or heatmap.py know that data belongs to the same sweep

### Actual behaviour
The timestamp progresses after each 32 datasets of a sweep

### Version information
**Operating system**: ubuntu 20.04 LTS

**hackrf_info output:**
hackrf_info version: git-8feda09
libhackrf version: git-8feda09 (0.7)
Found HackRF
Index: 0
Serial number: 0000000000000000088869dc2d82241b
Board ID Number: 2 (HackRF One)
Firmware Version: 2021.03.1 (API:1.04)
Part ID Number: 0xa000cb3c 0x00544755

I

**Comment by Chrysler2016** [comment]
I think you can remove "(long int)time_stamp.tv_usec" this part when you get the print.
this code is in function rx_callback(). only keep seconds.

from :
fprintf(outfile, "%s.%06ld, %" PRIu64 ", %" PRIu64 ", %.2f, %u",
					time_str,
					(long int)time_stamp.tv_usec,
					(uint64_t)(frequency),
					(uint64_t)(frequency+DEFAULT_SAMPLE_RATE_HZ/4),
					fft_bin_width,
					fftSize);
to :
fprintf(outfile, "%s , %" PRIu64 ", %" PRIu64 ", %.2f, %u",
					time_str,
					(uint64_t)(frequency),
					(uint64_t)(frequency+DEFAULT_SAMPLE_RATE_HZ/4),
					fft_bin_width,
					fftSize);
