### ISSUE TITLE
Some PortaPacks can cause 2021.03.1 firmware to hang during startup

### ISSUE THREAD

**Issue by miek** [greatscottgadgets/hackrf#1101]
Some PortaPacks seem to cause the firmware to hang during startup in `cpu_clock_pll1_max_speed` at the following line: https://github.com/greatscottgadgets/hackrf/blob/e9dd7eb291a770fbba18cdc72b3a50d0b033f9a2/firmware/common/hackrf_core.c#L533-L536

A git bisect found e12866f81ef482d05c2bf2526184cbc8e08d9020 to be the first failing commit.

DFU still works fine, and the firmware boots if the PortaPack is removed.

**Comment by martinling** [comment]
Fixed in #1106.
