### ISSUE TITLE
HackRF Sudden  Hardware Failure 

### ISSUE THREAD

**Issue by chakid21** [greatscottgadgets/hackrf#1104]
### Steps that Lead to Issue
1. Turned on HackRF & Portapack H2+ combo (that's been in light use for 1 month).
2. Turned device on and went to the main menu, no problem.
3. Walked away, came back.
4. Hackrf dead, no lights, no screen output on portapack, portapack power lights still.
5. Portpack responds to turning on and off, hackrf does not. Separated the portapack and plugged in hackrf direct with usb; nothing, no LEDs illuminate and the computer doesn't recognize any USB devices.

### Troubleshooting Accomplished

Tested multiple wires on 2 computers with different OSs.
Tested DFU procedures - no USB device recognized. 
The only thing the device seems capable of doing is charging the portapack.
Portapack acts the same regardless if it's connected to the HackRF or not. Turns on and off but nothing on display.

### Expected behavior
The ability to power on the HackRF

### Actual behavior
HackRF seems hard bricked.

### Version information
**Operating system**: Ubuntu 21.10 & Windows 10

**hackrf_info output:**
hackrf_info version: git-7047252
libhackrf version: git-7047252 (0.6)
No HackRF boards found.

### Third Party Software 

[Mayhem firmware v1.5.1 ](https://github.com/eried/portapack-mayhem/releases/tag/v1.5.1)

### Comment

I have no idea what caused this issue because there was nothing happening no Tx or Rx just dead from a main menu screen. I'd like to hope it's something as simple as a fuse but I need assistance troubleshooting. Adafruit (the merchant) refused to help troubleshoot and said they would only warranty it if someone from Great Scott Gadgets can say it's defective. Any help or support is greatly appreciated.

**Comment by straithe** [comment]
Can you post a picture of your HackRF (without the Portapack on it) here?

**Comment by chakid21** [comment]
![IMG_20220613_102950-01](https://user-images.githubusercontent.com/81959408/173411817-21405fc2-0b2d-41ea-8bc1-5a5b07470bb2.jpeg)

**Comment by straithe** [comment]
It look like this may be a hardware failure. Please contact your reseller for a replacement.
