### ISSUE TITLE
Compatibility test failed when trying to upgrade FW to 2021.03.1

### ISSUE THREAD

**Issue by pbartyik** [greatscottgadgets/hackrf#1108]
### Steps to reproduce
1. Connect HackRF while pressing DFU
2. dfu-util --device 1fc9:000c --alt 0 --download hackrf_one_usb.dfu
3.hackrf_spiflash -w hackrf_jawbreaker_usb.bin

### Expected behaviour
Board passes compatibility test.

### Actual behaviour
```
[user@host firmware-bin]$ hackrf_spiflash -v -w hackrf_jawbreaker_usb.bin
File size 27936 bytes.
Checking target device compatibility
Compatibility test failed.
[user@host firmware-bin]$
```

### Version information
**Operating system**: arch linux

**hackrf_info output:**

```
[user@host firmware-bin]$ hackrf_info
hackrf_info version: 2021.03.1
libhackrf version: 2021.03.1 (0.6)
Found HackRF
Index: 0
Serial number: 0000000000000000a06063c82508735f
Board ID Number: 2 (HackRF One)
Firmware Version: 2015.07.2 (API:1.00)
Part ID Number: 0xa000cb3c 0x0077435c
[user@host firmware-bin]$
```

**Comment by mossmann** [comment]
You are trying to install Jawbreaker firmware onto a device that identifies itself as a HackRF One. If the hardware is a HackRF One you should use the `hackrf_one_usb.bin` firmware image, not `hackrf_jawbreaker_usb.bin`. If the hardware is a Jawbreaker that erroneously had HackRF One firmware installed, try: `hackrf_spiflash -i -w hackrf_jawbreaker_usb.bin`
