### ISSUE TITLE
Dead usb

### ISSUE THREAD

**Issue by kreativdax** [greatscottgadgets/hackrf#1123]
Ok I have a dead usb have tried everything hackrf will go into Dfu but none of my computers communicate with hackrf. Tried many usb cables. Checked for blown or components getting hot none. Took portapack off still same put portapack on all works fine on portapack but still usb dead. Put portapack into hackrf mod usb is still dead no communication with a computer. Usb will power portapack but no data transfer at all. Checked resistor on pin 4 of usb cause that is Id pin it is fine too. Any help would be great

**Comment by straithe** [comment]
What operating system are you using?

What lights come on when the HackRF is plugged into a computer?

**Comment by kreativdax** [comment]
I fix it on the micro usb port pin 4 is ID port it has a 10k resistor on it i replaced resistor an now works fine.   I use Pentoo and Windows

**Comment by straithe** [comment]
To repeat back, you have solved the issue you were experiencing?

**Comment by kreativdax** [comment]
Yes

**Comment by straithe** [comment]
Thank you very much for the update.
