### ISSUE TITLE
Hack RF USB Not connecting to computer. 

### ISSUE THREAD

**Issue by npepper1** [greatscottgadgets/hackrf#1134]
I have a HackRF+Portapack 1.  I am trying to connect it to my computer via USB, but when I plug it into the USB, the light does not come on and the device does not show as connected on my computer.  The portapack did not come with a battery only USB connection. 

USB led does not light up and the device is not discoverable by Windows, MacOS or Linux. 
It is not shown in the Windows 10 Device Manager, or in the MacOS System Report, or found in Linux.
![IMG_1781](https://user-images.githubusercontent.com/19541658/185038644-8e6ab587-c382-4ffb-a5af-192a0368a6e1.jpeg)
![IMG_1782](https://user-images.githubusercontent.com/19541658/185038653-4b9b5e6a-7550-4646-bb6b-2a18d5f61ed6.jpeg)
![IMG_1783](https://user-images.githubusercontent.com/19541658/185038656-5ac3d78f-1500-4d8a-98ed-2920ba11d1c4.jpeg)
![IMG_1784](https://user-images.githubusercontent.com/19541658/185038663-a0230a66-3cb2-467f-83aa-a211d332879d.jpeg)

**Comment by straithe** [comment]
What happens when you try to plug in the HackRF without the Portapack attached?

**Comment by npepper1** [comment]
The same result as above.

**Comment by straithe** [comment]
How many different USB cables have you tried?
