### ISSUE TITLE
Running HackRF with different sample rate

### ISSUE THREAD

**Issue by fener1efes2** [greatscottgadgets/hackrf#1142]
[TEXBAT](https://radionavlab.ae.utexas.edu/texbat/) is a recorded dataset about spoofing scenarios for evaluating GPS signal authentication techniques.

On this project, there are recorded GPS signals stored as complex 16- bit samples at a rate of 25 Msps.

Maximum sample rate supported by HackRF is complex 8-bit samples at a rate of 20Msps.

How can I convert the file format and sample rate?

**Comment by martinling** [comment]
The typical way would be to set up a flowgraph in GNU Radio with a file source, resampler, and the necessary conversions. Then either send the result directly to a HackRF sink, or to a file sink to write converted files.

Or there's a standalone converter program [here](https://github.com/glv2/convert-samples) you might find useful.
