### ISSUE TITLE
Different HackRF One-s give inconsited behaviour

### ISSUE THREAD

**Issue by VasilyRakche** [greatscottgadgets/hackrf#1152]
### What would you like to know?

Hi, I have two HackRF One-s, but the behaviour is different between the two. Running the
[t1_checking_signals.zip](https://github.com/greatscottgadgets/hackrf/files/9487942/t1_checking_signals.zip), can be seen on the picture:
![image](https://user-images.githubusercontent.com/30003101/188401062-552c1357-f81e-4a66-a0f4-7d88ab23c432.png)  
With one HackRF I get the following:  
![hackRF_working_ok](https://user-images.githubusercontent.com/30003101/188401169-461f3b3a-93d3-48fe-8cfd-1b5234c812ee.png)  
And with the second one I get the following:  
![hackRF_working_strange](https://user-images.githubusercontent.com/30003101/188401242-8f428f28-4f19-4754-8e70-4d5a0f7f4935.png)

What is strange is the DC offset is different, I also noticed that the noise floor is a bit higher. What do you think?

**Comment by straithe** [comment]
Where did you get each HackRF from? Can you please post pictures of both?

**Comment by straithe** [comment]
To help me diagnose this can you please repeat the test with the RF gain set to 0. Ideally the test would be done with a cabled RF signal generator.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
