### ISSUE TITLE
[Technical Support]: Can't get FM stations to show on FFT plot, only single tone

### ISSUE THREAD

**Issue by jadams454** [greatscottgadgets/hackrf#1158]
### Can't get FM stations to show on FFT plot, only single tone

Hi,

HackRF newbie here. I am trying to run some basic code here, receive FM station. When I used a Soapy HackRF source and a QT GUI Frequency Sink, I only see one tone at the frequency that i specify for the HackRF. Nothing else around it. The lights on the side of the HackRF are on and RX is lit.

I am running Ubuntu, and when I run the hackrf_info command legit looking data shows up. All packages are updated.

I have updated the firmware to: 2021.03.1

What am I doing wrong?

![image](https://user-images.githubusercontent.com/17013397/190239595-bba3d719-f809-4d40-bdd4-0380fe1b26d1.png)

![image](https://user-images.githubusercontent.com/17013397/190239344-e5d08d0d-4a1f-4a41-82c4-7029c0a68216.png)

![image](https://user-images.githubusercontent.com/17013397/190239547-2e6a9e17-c2d9-4a87-bb79-a74952a9dfc8.png)

**Comment by straithe** [comment]
Please review the GNU Radio tutorials: https://wiki.gnuradio.org/index.php/Tutorials

**Comment by jadams454** [comment]
> Please review the GNU Radio tutorials: https://wiki.gnuradio.org/index.php/Tutorials

Will do, in the meantime is there an obvious gotcha here? Thanks!

**Comment by straithe** [comment]
You are hearing a tone so that seems fine. What are you hoping to have happen?

**Comment by jadams454** [comment]
See fm radio stations around the spectrum, a tone comes up where I set the
center frequency but no where else.

**Comment by jadams454** [comment]
> The spike/tone is the [DC offset](https://hackrf.readthedocs.io/en/latest/faq.html#bigspike).
> 
> 
> 
> You may need to turn up some gains in the source block. I assume you have a suitable antenna connected?

The antenna that came with it. I also saw that in the FAQ. I updated firmware. Not sure if this could be a version mismatch and how to tell?

![image](https://user-images.githubusercontent.com/17013397/190246222-c044e187-8a26-434b-94d1-f02cfb90b6d6.jpeg)

**Comment by jadams454** [comment]
> The spike/tone is the [DC offset](https://hackrf.readthedocs.io/en/latest/faq.html#bigspike).
> 
> 
> 
> You may need to turn up some gains in the source block. I assume you have a suitable antenna connected?

Also changing gains didn't help.

**Comment by dmaltsiniotis** [comment]
@jadams454 
For what it's worth, I've replicated the simple flow graph (on Windows) and it works as expected:
![image](https://user-images.githubusercontent.com/106233/190261769-5d06f882-e609-4adc-86c6-3c2ca6e8d0a2.png)
It could be that there's something off with the Soapy -> HackRF layer on your Ubuntu install. What I would recommend is installing the gr-osmocom (`apt-get install gr-osmosdr`) blocks and see if the problem persists. That will at least narrow it down:
![image](https://user-images.githubusercontent.com/106233/190262074-6242dc7c-4255-4e22-a6de-6499fd4c2265.png)

**Comment by straithe** [comment]
@jadams454 are you still looking for assistance or may I close this issue?

**Comment by jadams454** [comment]
All set thanks
