### ISSUE TITLE
[Tech Support]: HackRF Not Being Seen

### ISSUE THREAD

**Issue by KyleKaminky** [greatscottgadgets/hackrf#1170]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

I just installed Ubuntu brand new on my laptop and then installed gnuradio-companion, hackrf and gqrx. I was hoping to run hackrf_info and see my hackrf connected. I then tried installing hackrf from source.

### What outcome actually happened?

I am not seeing any connection and the usb light on my hackrf is not lighting up. When I plug it into my mac I do see the USB led illuminate and I am able to get results from hackrf_info

### What operating systems are you seeing the problem on?

Ubuntu 22.04.1

### What is the output of ```hackrf_info```?

hackrf_info version: git-e623c7ae
libhackrf version: git-e623c7ae (0.7)
No HackRF boards found.

### Are you using any third-party software?

I installed gnuradio with "sudo apt-get install gnuradio"
I installed gr-osmosdr with "sudo apt install gr-osmosdr"
I installed gqrx with "sudo apt install gqrx-sdr"

### Are you using any third-party hardware?

No

**Comment by straithe** [comment]
Thank you for reaching out. Have you tried a different USB cable?

**Comment by KyleKaminky** [comment]
Yes I have

**Comment by straithe** [comment]
I suggest trying ~5 different cables if you can. You are doing the right thing by checking `hackrf_info` after each cable. Another thing you could check is lsusb at the same time. There have been instances where the 5th cable works.

**Comment by KyleKaminky** [comment]
Holy crap haha. I honestly thought that was a little ridiculous, and what do you know.... the fifth cable worked!!! It also seems like the last cable I tried has the highest quality. Thank you for your help!

**Comment by straithe** [comment]
Happy to help! ☺️
