### ISSUE TITLE
[Question]: How do I know if my hackrf one  is broken?

### ISSUE THREAD

**Issue by Caglarr** [greatscottgadgets/hackrf#1201]
### What would you like to know?

Hi Dear Sir/Madam,

I tested my Hackrf One device with Gqrx. I'm trying to listen to a walkie talkie that does 150.55MHz Tx. When I tx with the handheld radio, there is an increase in the Gqrx frequency spectrum, but I cannot hear my speech on the handheld radio on the hack rf one side. There is too much noise. Do you think my device is broken? If it's not distorted, shouldn't I hear the sound clearly? Also, when I tried to listen to an FM radio frequency that I know, there was a lot of noise?

In addition, there were cases where I realized that the Antenna was not plugged in after I plugged in a hack rf one usb and energized it a few times. Maybe that's why it's broken? Can I test whether my device is OK from the Linux terminal?

![output_gqrx](https://user-images.githubusercontent.com/33661779/196268104-6076cbc7-a55e-4c84-b801-578136b8e43e.png)

**Comment by straithe** [comment]
Please open a technical support issue instead. Thank you.
