### ISSUE TITLE
[gr-ieee802.11/bastibl]: 

### ISSUE THREAD

**Issue by pococ31** [greatscottgadgets/hackrf#1211]
### What would you like to know?

While running the code from the GitHub repository [[bastibl](https://github.com/bastibl) /
[gr-ieee802-11](https://github.com/bastibl/gr-ieee802-11)
Public] in GNU radio companion ver 3.10
I replaced the UHD:USRP source with "Soapy HackRF source" but while running the code I get the error "s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s00s"

How to fix this issue ?

**Comment by straithe** [comment]
I suggest you leave an issue on the repository you link to in this issue since it seems that your issue is not with HackRF, but the software you are using, which I have no experience with. Thank you.
