### ISSUE TITLE
[Tech Support]: Help with GNU Radio

### ISSUE THREAD

**Issue by markl17** [greatscottgadgets/hackrf#1234]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

I tried the gnu radio 3.9 with soapy support which sucks to put it mildly so I downloaded 3.7 which has support for osmocom but it doesn’t seem to work at all even though I used the device driver and when I do hackrf_info it does work here is a link to what I am trying to accomplish 

### What outcome actually happened?

Nothing 
![9D66F82C-B68A-47CB-AF54-053052FFACE5](https://user-images.githubusercontent.com/768339/204133737-8c8a5841-3e82-4ac9-b30d-8982651bffe0.jpeg)

### What operating systems are you seeing the problem on?

Windows 11

### What is the output of ```hackrf_info```?

![648BEDBF-7B9E-4242-B33A-F1E15B9A7EE2](https://user-images.githubusercontent.com/768339/204134375-b64629bb-e941-43e1-a51b-45469e64a2a6.jpeg)

### Are you using any third-party software?

Gnu radio 

### Are you using any third-party hardware?

Hackrf and gnu radio to make signal generator

**Comment by straithe** [comment]
It looks like your issues are with GNU Radio and not HackRF One. I suggest reaching out to the GNU Radio community: https://www.gnuradio.org/ as they have some excellent resources.

**Comment by markl17** [comment]
I did contact them they told me that it is hackrf issue https://ham.stackexchange.com/questions/21537/using-3-10-gnuradio-and-hackrf-to-make-a-signal-generator

**Comment by straithe** [comment]
The link you have provided provides an answer using GNU Radio. Please implement the solution they have given you.

**Comment by markl17** [comment]
he output that you see on that webpage is what I am getting here. Here I am posting the whole thing

**Comment by markl17** [comment]
by the way I tried it with the original one with fried amp chip that still works and two new boards and none of them were recognized by gnuradio 3.10 which I got using conda install not brew. the hackrf stuff I installed using brew 
![IMG_3540](https://user-images.githubusercontent.com/768339/210771973-634a07d1-a8dc-4355-8940-47e27ce60fb0.jpg)
the one in the metal shield used to work on this mac before I it crashed and I had to reinstall the whole thing and I used conda not port because it is much quicker and simpler than recompiling the whole thing bringing in atleast 10 libraries which I seen port do any ideas

**Comment by markl17** [comment]
this is what i wrote in the other forum 
there is a chain of events to unravel why hackrf is being ignored and zadig doesnt load it with the proper driver and then gnuradio produce the proper diagram. the weakest link in all of this win 11 ignoring the hackrf for some unknown reason – 
same thing seems to happen in mac os 10.15 catalina I installed gnuradio with "conda install gnuradio" and hackrf with "brew install hackrf". hackrf doesn't detect the board I have three of them, the original with burned amp chip which still functions and new once. the original used to work like a charm and still seems to work and boots up, and yet still not recognized by hackrf
[markl17](https://ham.stackexchange.com/users/23099/markl17)
 [Dec 16, 2022 at 14:34](https://ham.stackexchange.com/questions/21537/using-3-10-gnuradio-and-hackrf-to-make-a-signal-generator#comment37909_21538)

**Comment by markl17** [comment]
My issue was resolved and it was because I didn’t research others reply’s. It was suggested that first and foremost one should check the cable. Most are made cheap, they don’t pass along anything but 5 volt pins
