### ISSUE TITLE
Create an histogram based on cfitsio library

### ISSUE THREAD

**Issue by alexmfz** [greatscottgadgets/hackrf#1240]
### What would you like to know?

Hi guys, 
I would like to know if you could be able to help creating a histogram based on cfitsio library.
I am looking for information but there is not enough documentacion about it and when I tried to open the .fits with JavaViewer, the log is the following:
![image](https://user-images.githubusercontent.com/47566168/207884072-f6c973a3-cec9-4061-9986-85334ccce7c2.png)

**Comment by straithe** [comment]
Can you please provide a link to the library you are talking about?

**Comment by alexmfz** [comment]
Ok, problem solved. It was about type of data. It should be BYTE data to print correctly at JavaViewer (from e-callisto)
