### ISSUE TITLE
Is there a low power mode for hackRF? 

### ISSUE THREAD

**Issue by alexmealster19** [greatscottgadgets/hackrf#1261]
### What would you like to know?

I'm working with a hackRF to run GNSS-SDR for a GPS fix. I have it working but the hackRF is consuming a lot of power. I was wondering if there was any way to configure the hackRF to potentially use less power. I am using an external oscillator and do not need to transmit.

**Comment by straithe** [comment]
No, HackRF One does not have a "low power" mode and there isn't really anything you can change that will make a big difference in how much power HackRF One uses. There are low power GPS receiver implementations, HackRF One is not one of them. Thanks for the question!

**Comment by straithe** [comment]
I'm closing this issue as the question has been answered.
