### ISSUE TITLE
HackRF One not connecting via USB anymore

### ISSUE THREAD

**Issue by WinstonVM** [greatscottgadgets/hackrf#1262]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

HackRF One 3v3, 1v8, RF, and USB light turns on when USB is plugged in

### What outcome actually happened?

3v3, 1v8, and RF is on, but USB is not lit

### What operating systems are you seeing the problem on?

Windows 10

### What is the output of ```hackrf_info```?

hackrf_info version: git-2b1aa545
libhackrf version: git-2b1aa545 (0.7)
No HackRF boards found.

### Are you using any third-party software?

GNU Radio Companion, SDR#

### Are you using any third-party hardware?

Portapack H2+

**Comment by straithe** [comment]
Have you tried using different USB cables? https://hackrf.readthedocs.io/en/latest/troubleshooting.html#why-isn-t-my-hackrf-one-detectable-after-i-plug-it-into-my-computer

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
