### ISSUE TITLE
HackRF One is not detecting on USB

### ISSUE THREAD

**Issue by nemopixels** [greatscottgadgets/hackrf#1263]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

It used to work normally. Now only the 3v3, 1VB and RF LEDs glow. USB LED does not glow.

### What outcome actually happened?

- Tried 5 different USB cables.
- Tried different computers, 2 windows, 1 Mac and 1 Raspberry pi 4B.
- Nothing shows up on lsusb, dmesg or hackrf_info. Same results with different cables, DFU mode. Please help!

### What operating systems are you seeing the problem on?

- 2 Windows hosts
- 1 Mac
- 1 Raspberry pi 4B

### What is the output of ```hackrf_info```?

Nelson:~ root# hackrf_info
hackrf_info version: unknown
libhackrf version: unknown (0.6)
No HackRF boards found.
Nelson:~ root#

### Are you using any third-party software?

SDRSharp

### Are you using any third-party hardware?

ANT500 or 700~5800 MHz Antenna.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
