### ISSUE TITLE
Reconnection/Reset hackrfOne

### ISSUE THREAD

**Issue by alexmfz** [greatscottgadgets/hackrf#1265]
### What would you like to know?

Hello guys,

I would like to ask you if It is possible to reset by SW hackrf One or reconnect It through cmd in VM. 
Sometimes, the hardware dies st sweeping so It could be interesting to do that.

**Comment by martinling** [comment]
Yes, you can reset an attached HackRF One with `hackrf_spiflash -R`.

**Comment by alexmfz** [comment]
Nice!
So just executing that, the device is reattach and Will I be able to sweep again?

**Comment by martinling** [comment]
Yes, although the sweep shouldn't be failing in the first place, so it would be good to hear more about the original problem. It sounds like you may be seeing similar problems to #1260 ?

**Comment by alexmfz** [comment]
My problem is that sometimes hackrfOne doesnt sweep so I have to exit from execution with CTRL+C.

**Comment by martinling** [comment]
Are you running the latest versions of the firmware and host software? If so, please open a bug report because that shouldn't happen.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
