### ISSUE TITLE
Symbol lookup error: ./hackrf_sweep: Undefined Symbol ....

### ISSUE THREAD

**Issue by alexmfz** [greatscottgadgets/hackrf#1271]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

I want to exec my own hackrf_sweep software based on yours

### What outcome actually happened?

Hi guys,

First of all, thank you so much with the question you are answering me. I am really having a nice help with the problems.

I would like to ask you about an error that has appeared at using hackrf API in a new environment. The case is the following:
I developed my hackrf_sweep code for my application and everything went well. However, When I moved the .zip from another PC, I have encountered the following error:

"Symbol lookup error: ./hackrf_sweep: undefined symbol....."

Do you know where is the problem? Could It that be because there are different versions of libraries?

Thank you so much :)

### What operating systems are you seeing the problem on?

I am using an Ubuntu

### What is the output of ```hackrf_info```?

N/A

### Are you using any third-party software?

N/A

### Are you using any third-party hardware?

N/A

**Comment by straithe** [comment]
Can you please add the output of hackrf_info to this issue?

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
