### ISSUE TITLE
HackRF with GNURadio send signal at 3.0GHz ~ 5.8GHz

### ISSUE THREAD

**Issue by jaehoon1001** [greatscottgadgets/hackrf#1274]
### What would you like to know?

Hi, 
I'm trying to send signal at 5.8GHz.
In 2.4Ghz, it is possible to send signal with hackrf and gnuradio.
but, 3.0GHz ~ 5.8GHz, I can't send signal.
I'm using hackrf, ANT500, and Ubuntu 20.04.
Is it my antenna issues? or something?
help me 🥲

**Comment by dmaltsiniotis** [comment]
@jaehoon1001 Can you elaborate on what you mean by "I can't send signal"? Is there an error message or some kind? Also, what are you using to send the signal, hackrf_transfer, GNU Radio, etc...

It's worth noting that the [ANT500's](https://www.greatscottgadgets.com/ant500/) specifications are listed as 75 MHz to 1 GHz. 5.8 GHz is well outside the antenna's operating frequency, so you'll need an antenna that operates in the frequency range you're working with.

**Comment by jaehoon1001** [comment]
What I meant was that even if I sent a signal to 5.8GHz with GNURadio, I could not get anything with gqrx. As you said, it might be an antenna problem. After changing the antenna, I'll check more. Thank you.

**Comment by martinling** [comment]
Note also that the [maximum transmit power](https://hackrf.readthedocs.io/en/latest/jawbreaker.html#transmit-power) of HackRF One is much lower at 5.8GHz than at 2.4GHz, so you may need higher gains on both the transmitter and receiver, as well as suitable antennas, to successfully receive a signal.

**Comment by jaehoon1001** [comment]
@martinling Wow, Thank you so much! With your answer, I can receive the 5.8GHz signal with the current antenna.

**Comment by martinling** [comment]
Great! Glad we could help.
