### ISSUE TITLE
Hackrf One not recognised anymore by host,  DFU works but firmware upgrade fails

### ISSUE THREAD

**Issue by avhoboken** [greatscottgadgets/hackrf#1280]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

hackrf one functioning correctly / connect properly to host

### What outcome actually happened?

device is not recognised anymore by Windows 10 or Ubuntu. In normal mode no device shows up in device manager. In DFU mode is does show NXP LPC device.
Also when running lsusb I see it is recognised properly 
![Schermafbeelding 2023-02-12 114637](https://user-images.githubusercontent.com/24414597/218306438-7afc00e2-3480-42ed-8552-cb6fa76563c1.png)

following the documentation I tried to recover the firmware by the below command but I guess the result is not ok:
dfu-util --device 1fc9:000c --alt 0 --download hackrf_one_usb.dfu 
![Schermafbeelding 2023-02-12 115203](https://user-images.githubusercontent.com/24414597/218306701-bba43cf4-7d9f-4337-9894-d6d6cc02e085.png)

Next also tried to upload the latest firmware but board is not found:
hackrf_spiflash -w hackrf_one_usb.dfu
![Schermafbeelding 2023-02-12 115421](https://user-images.githubusercontent.com/24414597/218306809-5bc6a283-79e2-4bcc-b53c-786b8c4f68c6.png)

### What operating systems are you seeing the problem on?

Both Windows and Ubuntu

### What is the output of ```hackrf_info```?

Even in DFU mode the board is not found
![Schermafbeelding 2023-02-12 114928](https://user-images.githubusercontent.com/24414597/218306579-f1178a86-21b0-4267-a31c-5432b0bc78d1.png)

### Are you using any third-party software?

n.a.

### Are you using any third-party hardware?

n.a.

**Comment by martinling** [comment]
The message `unable to read DFU status after completion` is normal and not a problem.

Once that `dfu-util` command has run, the NXP device should disappear and the HackRF One should show up. What do you see from `lsusb` and `hackrf_info` at that point?

It's important you don't unplug or reset the device before running `hackrf_spiflash`, since the firmware is only running from RAM at that stage.

Also note that the file you want to write with `hackrf_spiflash` is `hackrf_one_usb.bin`, not `hackrf_one_usb.dfu`.

**Comment by avhoboken** [comment]
and a copy of my board
![2023-02-12_11-59-38](https://user-images.githubusercontent.com/24414597/218307426-a6056a38-62b5-44c2-8103-1144be5d3a59.jpg)

**Comment by avhoboken** [comment]
Well good news, I already tried a few times before creating this issue but just run dfu-util again and now suddenly it shows hackrf device instead of the nxp device. Hackrf_info shows the below info and device is working again. 
![Schermafbeelding 2023-02-12 121425](https://user-images.githubusercontent.com/24414597/218307681-ec793794-074d-4d6c-b718-c9ed468a7ad4.png)
Thanks for your feedback !!

**Comment by martinling** [comment]
You still need to run `hackrf_spiflash` to write the `.bin` file. The firmware is still running from RAM (see serial number `RunningFromRAM` in the `hackrf_info` output) so it will be lost when you next reset the device.

**Comment by avhoboken** [comment]
Thanks, all works. Now next step is to get my portapack h2+ working again but for now I'm happy the the hackrf is working again :)
