### ISSUE TITLE
Issue attempting to view I2S bus at header P22

### ISSUE THREAD

**Issue by jaywebwar** [greatscottgadgets/hackrf#1284]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

I connected the HackRF One board to a laptop running CubicSDR. I have no issues connecting and receiving signals.
I tuned to a local FM station and can listen to it through the laptop speakers.
I hooked up a logic analyzer and probed pins 12-17 on P22.
I expect to see clks and data being sent across the bus.

### What outcome actually happened?

Signals on P22 (across the entire header) are a constant high or low.
There are no clocks and no digital data appears at P22.

### What operating systems are you seeing the problem on?

The laptop running CubicSDR is running Windows 10 Enterprise.

### What is the output of ```hackrf_info```?

hackrf_info version: git-7047252
libhackrf version: git-7047252 (0.6)
Found HackRF
Index: 0
Serial Number: 0000000000000000f77c60dc233d0fc3
Board ID Number: 2 (HackRF One)
Firmware Version: 2021.03.1 (API:1.04)
Part ID Number: 0xa000cb3c 0x00584361

### Are you using any third-party software?

CubicSDR

### Are you using any third-party hardware?

Saleae Logic analyzer

**Comment by straithe** [comment]
Thank you for your question. Please know that our firmware does not implement I2S.
