### ISSUE TITLE
Looking for Automatic Tuning LO Algorithm

### ISSUE THREAD

**Issue by Delta39** [greatscottgadgets/hackrf#1290]
### What would you like to know?

I'm trying to get insight into the frequency plan when AUTOMATIC_TUNING is TRUE. 

Could someone please point me to the section of code where LOs are calculated and passed to the RFFC5072 and MAX2837?

Thank you very much.

**Comment by martinling** [comment]
Hi! The main function for this is `set_freq` in `firmware/common/tuning.c`, which you can see the current version of [here](https://github.com/greatscottgadgets/hackrf/blob/master/firmware/common/tuning.c#L61-L128).

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
