### ISSUE TITLE
Hardware Sync not working on release 2023.01.1 

### ISSUE THREAD

**Issue by timtreutinger** [greatscottgadgets/hackrf#1292]
### What type of issue is this?

permanent - occurring repeatedly

### What issue are you facing?

Hey,
I wanted to sync two hackrfs using the hardware sync gpios. (https://hackrf.readthedocs.io/en/latest/hardware_triggering.html).
Both HackRFs were updated to release 2023.01.1. However, when running 

> hackrf_transfer -H -d <serial number> -a 0 -l 32 -g 32 -r rx1.cs8

with no external trigger connected, the HackRF would start receiving immediately. I reverted to release [2022.09.1](https://github.com/greatscottgadgets/hackrf/releases/tag/v2022.09.1) and now the HackRF is waiting for a trigger as it should.

Not sure if I did something wrong, as I am quite new to HackRF, but simply going to the older version fixed the issue for me, so it might be worth checking if this issue is present for you too on the new build.

### What are the steps to reproduce this?

Update to 2023.01.1 and run
> hackrf_transfer -H -d <serial number> -a 0 -l 32 -g 32 -r rx1.cs8
without external trigger, it should start writing data immediately to the file

**Comment by grvvy** [comment]
I've been able to reproduce this on OG boards; works on r9. Thanks for the find! Looking into it.
