### ISSUE TITLE
Show frequency 

### ISSUE THREAD

**Issue by samukas81** [greatscottgadgets/hackrf#1296]
Show in real time the frequency at the peak of the spectrum just like the Satsagen software.

**Comment by straithe** [comment]
Could you please describe this more? Where would you like the peak to be shown?

**Comment by samukas81** [comment]
this
![IMG_20230315_212804](https://user-images.githubusercontent.com/55217158/225478440-1b8b0b16-cd4d-46ef-8c9f-9484bf7278fa.jpg)

**Comment by straithe** [comment]
We don't provide a graphical user interface as part of HackRF that could visually show something like this. I suggest you ask the maker of the software you are using for visualizations to make such a feature.

**Comment by samukas81** [comment]
I'm sorry, I posted in the wrong place.

**Comment by straithe** [comment]
Ok. Thank you.
