### ISSUE TITLE
Hackrf portapack h2 does not send signals

### ISSUE THREAD

**Issue by pablozl85** [greatscottgadgets/hackrf#1300]
### What would you like to know?

Hello, I have a problem that my hackrf portapack h2  receives signals and does not send in any way reception tested on flipper zero car and other devices simply does not send a signal does anyone have any ideas for it? thanks in advance

**Comment by straithe** [comment]
I do not have experience with the portapack and cannot help you with that. Would you like help testing if your HackRF is working instead?

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
