### ISSUE TITLE
Is it possible to keep one of the port constant in the time mode for Opera Cake/what happens to A0 port during time mode?

### ISSUE THREAD

**Issue by nikstp** [greatscottgadgets/hackrf#1302]
### What would you like us to add to or change about the HackRF One documentation?

Hi, 

For PDDF FMCW experimentation I'm trying to keep one of the ports as a constant reference, but in reading the Opera Cake Modes of Operation page [documentation](https://hackrf.readthedocs.io/en/latest/opera_cake_modes_of_operation.html), it's not clear to me what happens to A0 port in time mode:

> In time mode, the A0 port connection switches automatically over time, counted in units of the sample period. This is useful for experimentation with pseudo-doppler direction finding.
> 
> To cycle through four ports, one port every 1000 samples:
> 
> `hackrf_operacake -m time -t A1:1000 -t A2:1000 -t A3:1000 -t A4:1000`
> 

In this example, does the Opera Cake actually switches between 5 ports? A0 -> A1 -> A2 -> A3 -> A4 -> A0? 

Also, a bit below:

> Only the A0 port connection is specified in time mode.

Which is not what's provided in the CLI snippets?  A0 is not used anywhere?

This just makes it confusing for me to understand whether I could use A0 as the reference signal port or if I'd have to choose a different one and skip it when putting Opera Cake into time mode. 

Thank you in advance!

**Comment by martinling** [comment]
I think this was answered in #1315.
