### ISSUE TITLE
Integration time HackRF

### ISSUE THREAD

**Issue by alexmfz** [greatscottgadgets/hackrf#1304]
### What would you like to know?

Hello guys, 

I would like to ask you about a feature which I cannot find. It is about the integration time. What is the value of it? Is it defined somewhere?

Thank you,
Best regards :)

**Comment by straithe** [comment]
I do not know what you mean by 'integration time'. Could you please share more information about your use case?

**Comment by straithe** [comment]
To clarify, are you referring to the hackrf_sweep command?

**Comment by alexmfz** [comment]
Yep, I am referring to that yes

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
