### ISSUE TITLE
HackRF USB not recognized

### ISSUE THREAD

**Issue by cielobao** [greatscottgadgets/hackrf#1305]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

Establishing a connection between the device (Great Scott Gadgets Hack RF One) and the intended operating system.

### What outcome actually happened?

3V3 Light : Green
1V8 Light: Yellow
RF Light: Red
RX, TX: Off

System running Kali Linux (rolling) on RPi 4 [aarch64 | Linux kali-raspberry-pi 5.15.44-Re4s...] No USB ACK.
>$ hackrf_info
Returned;
hackrf_info version: 2022.09.1
libhackrf version: 2022.09.01 (0.7)
No HackRF boards found.

Figured it may not have been installed as a module, so I ran 
>$ lsmod 
*No hackrf module listed*

Attempt to load the module failed:
>$ sudo modprobe hackrf
Returned;
modprobe: FATAL : Module hackrf not found in directory /lib/modules/5.15.44-Re4son-v8l+

>$ sudo apt-get update
>$ sudo apt-get install hackrf
Returned;
hackrf is already the newest version

Attempted modprobe again, same result.

>$ lsmod | grep rf
Returned;
rfcomm
rfkill

Reinstalling hackrf
>$ sudo apt-get install --reinstall hackrf
Success

Ran lsmod | grep rf again; no hackrf found
Ran sudo modprobe hackrf again; same fatal error

Checked USB ports
>$ lsusb -v -D [all ports]
None of the displayed information corresponding to hackrf despite there being power to the device.

I decided to change the USBB cable from the one with the original packaging, tried 5 total micro usb cables in total.
Used 2 USB to USBC with micro B adapters, still no change or acknowledgement.
*also plug into all usb ports, on all systems, with all wires.*

Tried connecting to Windows 10 laptop. No ACK. Used all 7 cables, same effect.
Tried connecting to MacOS Ventura 13.3.1 with all 7 cables, same effect. No ACK.

Reset button held for one - two seconds, when pressed; 3V3 remains green, 1V8 turns off, RF remains red, no change from remaining indicators.  HackRF hardware inspected, no visible damage noted inside. 

Had the privilege  to test the hardware at it's early dev. I've used it here and there, it's been kept in it's box. Used lightly and never overexposed to high input while tested. 

![img001](https://user-images.githubusercontent.com/98973936/230787525-f65b0f6c-76b7-4327-8bfc-1abc57d06a41.jpg)

### What operating systems are you seeing the problem on?

Kali Linux (rolling) on RPi 4 [aarch64 | Linux kali-raspberry-pi 5.15.44
Windows 10 laptop arch.64
MacOS Ventura 13.3.1 arch.64

### What is the output of ```hackrf_info```?

hackrf_info version: 2022.09.1
libhackrf version: 2022.09.01 (0.7)
No HackRF boards found.

### Are you using any third-party software?

N/A

### Are you using any third-party hardware?

N/A

**Comment by straithe** [comment]
Thank you for your report. I notice you tried quite a few micro USB cables, were they all from different sources, vendors, or shops? Or were they all from the same package of cables?

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
