### ISSUE TITLE
#1295 Deletes API Docs

### ISSUE THREAD

**Issue by alexanderturner** [greatscottgadgets/hackrf#1308]
### What would you like us to add to or change about the HackRF One documentation?

And Alex is sad.

**Comment by straithe** [comment]
I do not understand what you are asking for with this issue.

**Comment by straithe** [comment]
API will be documented via Doxygen once https://github.com/greatscottgadgets/hackrf/pull/1244 is completed.

**Comment by alexanderturner** [comment]
Thanks and I see this PR - currently, however, there are no publicly accessible API docs for developers to use

**Comment by straithe** [comment]
PR #1244 is public and you are welcome to build the API docs from that branch until we merge it into our documentation. We hope that merge will be soon. We are waiting on some final fixes from the contributor.
