### ISSUE TITLE
Getting an array of amplitudes in C++

### ISSUE THREAD

**Issue by RelictRLCT** [greatscottgadgets/hackrf#1313]
### What would you like to know?

Hello, I would like to get an array covering the entire frequency range and storing the amplitudes at each frequency (possibly with some frequency step, for example 99 MHz, 99.1 MHz and so on). I have a problem with the hackrf_start_rx function. This is what my callback function looks like:
int callback(hackrf_transfer* transfer) {
     
        uint8_t* buffer = (uint8_t*)transfer->buffer;
        int buffer_length = transfer->buffer_length; 

        freq.clear();
        amp.clear();

        for (int i = 0; i < buffer_length; i += 2) {
            double real = buffer[i];
            double image = buffer[i + 1];
            double amplitude = sqrt(real * real + imag * imag);

            freq.push_back(i / 2); 
            amp.push_back(amplitude);
        }

        return 0;
    }
But freq and amp arrays contain an average of 2900 - 3000 values. What can I do to expand the program to the full spectrum?

**Comment by martinling** [comment]
The data passed to the callback is time series IQ sample data, not per-frequency values. To get results in the frequency domain you need to apply a Fourier transform. This is what's done in `hackrf_sweep`, for instance.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
