### ISSUE TITLE
Unknown Board ID

### ISSUE THREAD

**Issue by MarcD250** [greatscottgadgets/hackrf#1317]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

I've recieved my HackRF One a few days ago and wanted to flash the Portapack Firmware to it. The main problem is that the HackRF is not found/not compatible:
![grafik](https://user-images.githubusercontent.com/132677555/236539118-c98e5288-0ec8-4e40-b443-0a2b085a90f3.png)

### What outcome actually happened?

I wasn't able to flash new firmware

### What operating systems are you seeing the problem on?

Linux Ubuntu

### What is the output of ```hackrf_info```?

mr@mr-CF-53SNXBYFG:~$ hackrf_info
hackrf_info version: unknown
libhackrf version: unknown (0.6)
Found HackRF
Index: 0
Serial number: 0000000000000000f75461dc2669a6c3
Board ID Number: 4 (Unknown Board ID)
Firmware Version: 2023.01.1 (API:1.07)
Part ID Number: 0xa000cb3c 0x00664761

### Are you using any third-party software?

No, just want to use my Portapack

### Are you using any third-party hardware?

Portapack H2, but not yet used because of the flashing issue

**Comment by martinling** [comment]
Please see the guide at:

https://hackerwarehouse.tv/product-knowledgebase/portapack-h2/hackrf-one-r9-and-portapack-compatibility/

**Comment by MarcD250** [comment]
I did everything according to this guide.. but without success :-(

**Comment by MarcD250** [comment]
I'm Just curious because hackrf_info tells me that the Board ID is 4 (Unknown)

Board ID Number: 4 (Unknown Board ID)

Any ideas why it's Unknown?

**Comment by martinling** [comment]
It's unknown because you're running an old version of libhackrf and the host tools which predates the r9 hardware. If you update to the current 2023.01.1 release, it will recognise that board ID.

**Comment by MarcD250** [comment]
That was also my thought, but I tried installing new software via 'sudo apt-get install hackrf' 
But the Installer found nothing new..

**Comment by straithe** [comment]
apt-get will not get you the latest versions of libhackrf and the host tools. You will have to build from the repository.

**Comment by MarcD250** [comment]
Thank you! I'll give it a try.

**Comment by MarcD250** [comment]
Hello, it worked! 
![grafik](https://user-images.githubusercontent.com/132677555/236629594-a3054068-14ba-407f-8b14-a2580a72c987.png)
Thanks for all the help!

**Comment by Metalblade66** [comment]
> apt-get will not get you the latest versions of libhackrf and the host tools. You will have to build from the repository.

How can I do it?
