### ISSUE TITLE
Amplifying hackrf transmit signal

### ISSUE THREAD

**Issue by mjcuc** [greatscottgadgets/hackrf#1318]
### What would you like to know?

I'm considering of testing following setup
![image](https://user-images.githubusercontent.com/129488032/236662559-fc289331-b687-4022-a5f5-ac6a76665689.png)

Is there any change this setup will work?

Any risks of damaging HackRF?

**Comment by straithe** [comment]
Can you please give more detail such as what you are trying to do, what results you hope to achieve, etc?

**Comment by mjcuc** [comment]
Basically the following test setup on 70cm band (I have a repeater nearby):
https://www.youtube.com/watch?v=rTp6vQk5MqE

Of course, a real antenna is connected only after serious testing and with required ham licensing.

**Comment by martinling** [comment]
I think this would work OK. I don't think you need any delay.

The TX/RX LEDs are switched just before the internal RF path is changed: see [here](https://github.com/greatscottgadgets/hackrf/blob/master/firmware/hackrf_usb/usb_api_transceiver.c#L318-L344) in the firmware code. So when the LED goes on/off seems like exactly the right moment to switch your external RF path as well.

Another way to control this, without needing to run extra wires to the HackRF, would be to use the built-in bias tee. This can be turned on and off by the host, and we have a PR open at the moment which enables turning it on automatically during TX (#1314). You'd need to include an RF choke and a coupling capacitor on your amp board to separate the 3.3V DC signal from the RF.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
