### ISSUE TITLE
Damaged antenna connector, replaced it, still no signal

### ISSUE THREAD

**Issue by TLMcNulty** [greatscottgadgets/hackrf#1320]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

Was hoping FM commercial radio/433 locally triggered signals to be visible. 

### What outcome actually happened?

Waterfall remains very quiet. 

### What operating systems are you seeing the problem on?

Windows/Linux

### What is the output of ```hackrf_info```?

Working correctly, this is a hardware problem as a result of idiocy. 

### Are you using any third-party software?

No

### Are you using any third-party hardware?

Operacake, Rasp pi, MFJ antenna switchers, UPS, etc.

**Comment by straithe** [comment]
Can you please send me the output of hackrf_info?

**Comment by straithe** [comment]
Can you also please add a picture of your board to this issue?

**Comment by TLMcNulty** [comment]
Not sure why the versions are coming in as unknown, this is not the usual device I connect to the board with.

```
➜  ~ hackrf_info
hackrf_info version: unknown
libhackrf version: unknown (0.6)
Found HackRF
Index: 0
Serial number: 0000000000000000088869dc2426911b
Board ID Number: 2 (HackRF One)
Firmware Version: 2022.09.1 (API:1.06)
Part ID Number: 0xa000cb3c 0x006a4763
```

![PXL_20230512_185324998](https://github.com/greatscottgadgets/hackrf/assets/8993166/f5f28476-bb0e-49a0-b73e-3b871672c64a)
![PXL_20230512_185319715](https://github.com/greatscottgadgets/hackrf/assets/8993166/b14c2d0e-2b74-49aa-977e-0cabbc71fd32)

**Comment by straithe** [comment]
It looks like the connector on the right hand side of the last picture needs to be re-soldered and cleaned up. Some of the solder from that workmanship seems to have travelled to at least one nearby via and possibly another component. I am not quite sure as the picture isn't very clear on close up. Please try that fix and let me know if you see changes. 

Do you have a link to the connectors that you substituted on? I'm curious about the component and why you made the switch.

**Comment by TLMcNulty** [comment]
Yeah it's a hard to solder both sides of that connector effectively, and I think the pins on the replacement are a bit too long. Thanks for confirming the vias can't be bridged. It might be touching one other component as well. It'll be hard to rework. 

The damaged component was originally torn/bent. I removed the torn flap and finished the rough edges to result in basically a chunk missing. Reception quality was greatly impacted. 

![PXL_20230706_201811037 MP](https://github.com/greatscottgadgets/hackrf/assets/8993166/94444e0f-cd69-4dee-a261-5bdf3b5fd2d6)
![PXL_20230706_201749321 MP](https://github.com/greatscottgadgets/hackrf/assets/8993166/46c8fef5-cc8a-4be9-ade5-c867c7469e91)

**Comment by straithe** [comment]
Rework is your primary path to fixing your device at this point. Hopefully it goes well!
