### ISSUE TITLE
HackRF not detected via USB

### ISSUE THREAD

**Issue by oliverwolfat** [greatscottgadgets/hackrf#1326]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?
Unfortunatley the troubleshooting guide is no longer available, i need some assistance troubleshooting the HackRF One
yes

### What outcome were you hoping for?

HackRF One being detected by the host computer

### What outcome actually happened?

HackRF One not showing up in either Normal nor DFU mode.
Windows:
Not showing up in Device Manager neither in Normal nor in DFU mode

Kali Linux:
Not showing up in lsusb or dmesg neither in Normal nor in DFU mode

I tried around 5 different cables from different brands, different devices.

HackRF Board:
![Normal_mode](https://github.com/greatscottgadgets/hackrf/assets/19332227/6e6ed762-ce27-48ef-8d22-d4e3922700f9)

Normal Mode:
3V3, 1V8, RF are fully lit

DFU Mode:
![DFU_mode](https://github.com/greatscottgadgets/hackrf/assets/19332227/3b6f692e-90bf-4f54-8bb2-7acd9d22bfb2)
3V3, RF fully lit
TX dimly lit

Revision r4_p1
MCU gets extremely hot

### What operating systems are you seeing the problem on?

Microsoft Windows 10 Pro 22H2
Kali Linux 6.1.0

### What is the output of ```hackrf_info```?

There is no Output, since the device is not detected

### Are you using any third-party software?

Not able to use any Software with it

### Are you using any third-party hardware?

No additions made

**Comment by oliverwolfat** [comment]
I did some digging and found the troubleshooting steps from #684 
I measured the resistance on the micro USB connector with the following results.

Pin 1 (VCC) to Pin 5 (GND): 9.98 kOhm
Pin 2 (D-) to Pin 5 (GND): 1,623 MOhm
Pin 3 (D+) to Pin 5 (GND): 1,549 MOhm
Pin 4 (ID) to Pin 5 (GND): 10 kOhm

**Comment by straithe** [comment]
How many different cables have you tried? https://hackrf.readthedocs.io/en/latest/usb_cables.html

**Comment by oliverwolfat** [comment]
As stated in my original post, i tried 5 cables from 5 brands. 

I have a hackrf clone laying around as well, which has been detected by the host computer with all 5 cables.

I also tried three host pcs (2x Windows, 1x Linux) and different ports

**Comment by oliverwolfat** [comment]
I have tried a sixth cable today, different style Micro USB to USB-C same results

**Comment by straithe** [comment]
Are you connecting direct to the computer or through a USB hub?

**Comment by oliverwolfat** [comment]
I am connecting directly via computer, but i also tried it via Hub. I can't say if it is powered or not, it has a power Delivery port (Anker USB-C Dock)

**Comment by straithe** [comment]
I am curious and have one more question about the cables you've tried. Are they all micro to USB-C, or have you tried some that are micro to USB-A?

**Comment by oliverwolfat** [comment]
Hi straithe,

I have tried about 7 different USB-A to Micro-USB cables (with and without the USB-C dock in between) and 2 different USB-C to Micro-USB cables (only without the USB-C dock) on 3 different devices.

KR
Oliver

**Comment by straithe** [comment]
I suggest contacting your reseller to see if they will exchange your HackRF.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
