### ISSUE TITLE
USB test points?

### ISSUE THREAD

**Issue by Commander-Crash** [greatscottgadgets/hackrf#1331]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

I want to know where USB test points are located on the hackrf one board.

### What outcome actually happened?

To replace faulty microusb with USB C brakeout port

### What operating systems are you seeing the problem on?

Not Available this is hardware question.

### What is the output of ```hackrf_info```?

Not Available this is hardware question.

### Are you using any third-party software?

Not Available this is hardware question.

### Are you using any third-party hardware?

Not Available this is hardware question.

**Comment by straithe** [comment]
There are no USB test points on the HackRF One board. The Micro USB connector is used.

**Comment by Commander-Crash** [comment]
To anyone looking for a way for USB out.
![20240717_153011](https://github.com/user-attachments/assets/db709dc2-6ee3-46d7-96ab-fbc73c3a2079)
