### ISSUE TITLE
Get 4 seperate samples from each antenna on the A side in time mode in python

### ISSUE THREAD

**Issue by ozgurgunesulkesi** [greatscottgadgets/hackrf#1332]
### What feature would you like to see and why?

Hi,

I would like to try a direction finding method with the hackRF and operacake but not using the pseudo Doppler instead power of arrival with 4 logperiodic antennas. Therefor I need four clean separated samples from each antenna port. I am using pyhackrf as a wrapper around libhackrf to get samples. But how do I need to set the hackrf_operacake tool.

**Comment by peter-stricher** [comment]
Ok thank you for the reply. I will test this one

**Comment by straithe** [comment]
@ozgurgunesulkesi did the instructions from @martinling solve the issue you were experiencing?

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
