### ISSUE TITLE
HackRF One Receiver Not Working As Expected

### ISSUE THREAD

**Issue by jlinehan** [greatscottgadgets/hackrf#1336]
### What would you like to know?

I recently bought two HackRF One receivers that I intended to use with existing software. The software was based on a 2018.01.1 version of the software and it runs on an ODroid device. The software runs perfectly on the old receiver but not on either of the new receivers.

I installed hackrf and dfu_utils on the ODroid and can run hackrf_sweep without issues.

When I run hackrf_info the new receivers reported a serial number "RunningFromRAM", board ID 4 (Unknown Board ID), and API 1.07.

When I run hackrf_info with the old receiver it reports a normal serial number, API 1.02, board ID 2 (HackRF One).

I cannot run hackrf_spiflash or dfu_util successfully.

Is the board initialized and if not how do I initialize it?

**Comment by straithe** [comment]
I have some clarifying questions:
* What existing software are you intending to use your HackRF Ones with? 
* What are you referring to when you say "old receiver"? Is the device you are referring to another HackRF One, or a different device?
* Can you please add a screen shot of your ```hackrf_info``` output to this issue?

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
