### ISSUE TITLE
Receiving and transmitting problem.

### ISSUE THREAD

**Issue by ArekPL77** [greatscottgadgets/hackrf#1338]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

N/A

### What outcome actually happened?

I have a problem that I cannot solve. Please advise.
I bought my first HackRf device a few years ago, it worked flawlessly until a path on the PCB from the antenna socket broke. I added a piece of wire between the antenna socket and the resistor on the PCB, but the device no longer worked as before. It transmits and receives with very low power. I have now bought a new device - and here's a surprise it transmits and receives just as poorly as the old damaged device.

I understand that a component in the old one was damaged, but why does the new one have the same problem? Please advise why this is so?

What component was damaged in the old device? Can I replace it myself?

I am attaching pictures showing the remote control signal reception from the RTL-SDR and the damaged and new HackRF to show how poorly they receive signals. At HackRF I marked the signals with a circle, you can hardly see them.

![RTL-SDR](https://github.com/greatscottgadgets/hackrf/assets/134891657/04ea98c5-45d3-43b6-bf2a-4c698fc97e74)
![HackRF broken](https://github.com/greatscottgadgets/hackrf/assets/134891657/7017955a-f1ed-490a-918b-23935ada0e02)
![HackRF new](https://github.com/greatscottgadgets/hackrf/assets/134891657/9adf1556-3ece-49e1-b2a9-e2f3452b6cf0)
![old one front](https://github.com/greatscottgadgets/hackrf/assets/134891657/52787757-b897-4f27-980a-f4722e01eab9)
![old back](https://github.com/greatscottgadgets/hackrf/assets/134891657/75979229-e89d-4bad-a4fd-1927f3ae5a09)
![new one back](https://github.com/greatscottgadgets/hackrf/assets/134891657/3d660ff4-72dc-4e61-8e73-559ff2c924f8)
![new one front](https://github.com/greatscottgadgets/hackrf/assets/134891657/6a65b93b-34e9-432f-b4c6-0a01d0caaaed)

### What operating systems are you seeing the problem on?

Windows 10

### What is the output of ```hackrf_info```?

N/A

### Are you using any third-party software?

SDRSharp

### Are you using any third-party hardware?

original antenna

**Comment by straithe** [comment]
I am closing this issue as a duplicate to #1333
