### ISSUE TITLE
how the hackrf work longer?

### ISSUE THREAD

**Issue by seniorjack** [greatscottgadgets/hackrf#1343]
### What would you like to know?

I got a new hackrf and make a gps-sim-test, but it work about one hour, but i could not work more than one hour. I feel it's not very hot , why it could not work longer?

it is R9 version

**Comment by straithe** [comment]
What do you mean by 'it works about one hour'? Is it a program you are running that is lasting for an hour? Does your computer shut off after an hour? Does the HackRF lost power after an hour. I need a lot more context to be able to assist you.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
