### ISSUE TITLE
Is it possible to change the transmission frequency during broadcasting?

### ISSUE THREAD

**Issue by ZxUkr** [greatscottgadgets/hackrf#1357]
Can I use hackrf_set_freq() inside receive/transmit callback function for change carrier frequency for all next data during broadcast?
Will it be work correct?
How long hackrf_set_freq() is taken?

**Comment by ZxUkr** [comment]
So only exist way to change transmission frequency is throuth:
0) flush_callback
1) hackrf_stop_tx
2) hackrf_set_freq
3)hackrf_start_tx
?

Is it exist more fast way to change frequency?

**Comment by VioletGiraffe** [comment]
I am also interested in the fastest way to change the frequency during transmission, can we please get an official, developer-approved canonical answer / algorithm? Thanks!

**Comment by VioletGiraffe** [comment]
Great answer, appreciate it. So there's no problem with changing the frequency while transmission is running, only with changing it from the async callback call stack. That is, apart from the reasons why one might not want to change it on the fly at all.
