### ISSUE TITLE
Which MOSFETs and high-pass filters are used in HackRF?

### ISSUE THREAD

**Issue by surpscare** [greatscottgadgets/hackrf#1364]
I've got my RX amplifier additional transistor (Q1) fried, so once I enable the AMP tick in the receiver, the sensitivity drops significantly, and the driving MOSFET begins to heat up so much that it starts producing a light smoke. The MGA-81563 itself is still intact though, and it does not make any heat, but the absence of additional power from the transistor makes it closely unable to receive something at the 5G band from a distance of more than 10 centimeters away. Which SMD transistor can be used for replacement?
Also, for some reason, the Highpass SAW filter broke down, despite that all other elements in the chain including SKY13350's are okay, and the device got nearly blind to anything above 2740MHz and also no TX output at all. I had to short-circuit it to regain the ability to RX/TX in the microwave band, but now the mirror signals from the lower bands are present, so an external filter must be used to eliminate them. Which SAW filter can be used for a replacement?

**Comment by martinling** [comment]
The original part for Q1 is Yangzhou Yangjie YJL2301C. Many similar transistors could also be used. The DC supply current that it needs to carry to the MGA-81563 is at most around 50mA, but allow plenty of headroom on the current rating.

The original part for the highpass filter U8 is TDK DEA162400HT-8004B1. This is out of production, but there are similar types available that could be substituted, such as DEA162400HT-8053A1.

Note that the full BOM can be found in the [release packages](https://github.com/greatscottgadgets/hackrf/releases) from this repository, in `doc/hardware/hackrf-one-bom.csv`. Part numbers are also included in the KiCAD schematic files.
