### ISSUE TITLE
Verifying external clockinput and 1pps on HackRF SDR

### ISSUE THREAD

**Issue by swapnachallagundla** [greatscottgadgets/hackrf#1369]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

How to test if the external 10MHz and 1pps inputs are activated or not on Hack Rf radio?

### What outcome actually happened?

I want to synchronize multiple hackrfs installed at different places. I am using GPSDO for generating 10MHz clock input and 1 PPS  for frequency and time synchronizations. I connected 10MHz at CLOCKIN input and 1pps at pin 16 of P28 on HackRF. Now I want to test whether these two signals are actually detected or not. 
I used the command "hackrf_clock -i" to check it. But I did not get anything.

I also tried to use this command  "hackrf_debug -s -n 0 -r" in terminal during transmission/reception. But it displaying the message hack rf already in use.

### What operating systems are you seeing the problem on?

Linux

### What is the output of ```hackrf_info```?

N/A

### Are you using any third-party software?

N/A

### Are you using any third-party hardware?

N/A

**Comment by mmm545** [comment]
> I also tried to use this command "hackrf_debug -s -n 0 -r" in terminal during transmission/reception. But it displaying the message hack rf already in use.

Did you try running the command while NOT receiving/transmitting? Because that's what you're supposed to do.

**Comment by swapnachallagundla** [comment]
Yes, I tried. It returned 0x51 when I run the above command. 

Do I need to run any commands after connecting these external inputs?

**Comment by swapnachallagundla** [comment]
When I run the command hackrf_debug --si5351c -n 0 -r on r6 model it displays 0x01

and when I run the same command on r8 and r9 models it displays 0x51.

Also, hackrf_clock -i is not working and it displays invalid option when I run this command.

**Comment by martinling** [comment]
You should use `hackrf_clock -i` to check for the presence of the external clock input. This needs to be run when the HackRF is not in use by other software. If a clock is detected on CLKIN, it will be used automatically when TX/RX is started.

The old way of checking this using `hackrf_debug` is deprecated, and does not work with all hardware revisions.

You can check that the 1PPS input is working by running `hackrf_transfer` with the `-H` option for hardware triggering:

`hackrf_transfer -r /dev/null -H` 

This should display `Waiting for trigger...` and then start reception on the next 1PPS pulse.

**Comment by martinling** [comment]
> Also, hackrf_clock -i is not working and it displays invalid option when I run this command.

Then you should update your host tools to a newer version, which will have this option.

**Comment by swapnachallagundla** [comment]
We are using the latest version r9 of hackrf which is updated firmware.

**Comment by martinling** [comment]
Yes, but if your `hackrf_clock` does not have the `-i` option then your host software is older than that. That option was added #1135 and included in the 2022.09.1 release.

**Comment by swapnachallagundla** [comment]
Thanks.
 I have updated host software. Now, I am able to detect clock and 1pps is also working.

**Comment by martinling** [comment]
Great! Glad we could help.
