### ISSUE TITLE
Will the RTL-SDR “V-Dipole” Antenna Work for Reception?

### ISSUE THREAD

**Issue by AlexLandherr** [greatscottgadgets/hackrf#1373]
### What would you like to know?

I have an old RTL-SDR “V-Dipole” Antenna Kit left and since the HackRF One uses a SMA connector for its antenna connector I suspect that my old kit would work okay; is this likely true?

I plan on using it for NOAA APT reception.

**Comment by martinling** [comment]
Yes, I expact that should work fine.
