### ISSUE TITLE
What Does This Handwriting on the PCB Mean?

### ISSUE THREAD

**Issue by AlexLandherr** [greatscottgadgets/hackrf#1376]
### What would you like to know?

Today I received my HackRF One unit and when I proceeded to open it to put in the Nooelec metal case with the “Tiny TCXO” I found this handwriting on a white and rectangular area:
![D1C23A62-ADD7-4419-9CFF-682EA5333C5D](https://github.com/greatscottgadgets/hackrf/assets/86981389/2e4eac56-8ded-4e06-a82c-0a9566b9362e)

I bought my unit from a seller listed by Great Scott Gadgets as being in the Netherlands.

My suspicion is that’s it’s nothing bad but I just want to be as sure as possible.

**Comment by martinling** [comment]
This is normal. Our boards are 100% tested. After they go through testing, they are marked by hand with the ID of the test run, as part of the QA process.

**Comment by AlexLandherr** [comment]
Ok, understood! Didn't expect it. Will soon try my new unit with SDR# on Windows 10.
