### ISSUE TITLE
no modulation on rev 9 board reicive works

### ISSUE THREAD

**Issue by rkalasek1** [greatscottgadgets/hackrf#1393]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

what do i need to do to fix this

### What outcome actually happened?

wont modulate signal on any band signal is clear but no modulation

### What operating systems are you seeing the problem on?

all

### What is the output of ```hackrf_info```?

n/a

### Are you using any third-party software?

mayhem

### Are you using any third-party hardware?

portapack    the portapak works on my other board

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
