### ISSUE TITLE
max2839ETN+ stock

### ISSUE THREAD

**Issue by muratkarahan** [greatscottgadgets/hackrf#1394]
### What would you like to know?

Hi,
For Revision 9, i need max2839ETN+. But its  status is seen obsolete for many authorized distributor network. There are also different distributers to support obsolete components. Can you suggest any provider for max2839ETN+.

thanks

**Comment by martinling** [comment]
I doubt there's any stock left of MAX2839. The part is obsolete, and was only used because there was some remaining stock of it available at a time when there were shortages of MAX2837. Earlier and current revisions use MAX2837.
