### ISSUE TITLE
Hackrf ONE deaf?

### ISSUE THREAD

**Issue by ariaveta** [greatscottgadgets/hackrf#1397]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

no, because that link is broken. I read the docs here: https://hackrf.readthedocs.io/en/latest/index.html

### What outcome were you hoping for?

After connecting a GNURadio waterfall on FM band (88-108 MHz) I expect to see many FFT peaks. After connecting a GQRX receiver I expect to see a lot of signals and to be able to listen FM radios.

### What outcome actually happened?

No FM station signals in the samples captured by the radio. Another Hackrf ONE board in the same conditions is working fine.

### What operating systems are you seeing the problem on?

Linux Ubuntu 20.04 

### What is the output of ```hackrf_info```?

hackrf_info version: git-4b31fd91
libhackrf version: git-4b31fd91 (0.8)
Found HackRF
Index: 0
Serial number: 0000000000000000675c62dc310c48cf
Board ID Number: 4 (HackRF One)
Firmware Version: 2023.01.1 (API:1.07)
Part ID Number: 0xa000cb3c 0x00584f59
Hardware Revision: r9
Hardware appears to have been manufactured by Great Scott Gadgets.
Hardware supported by installed firmware:
    HackRF One

### Are you using any third-party software?

GNURADIO, gqrx

### Are you using any third-party hardware?

no

**Comment by straithe** [comment]
I believe your issue will be fixed if you update to the latest version of the firmware.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
