### ISSUE TITLE
DVT-T

### ISSUE THREAD

**Issue by iz5tep** [greatscottgadgets/hackrf#1408]
### What feature would you like to see and why?

Hi, I would like to know if it is possible to implement rtx in dvb-t.
DVB-S transmission is excellent, but DVB-T is missing at low ksr, 500/1000 ksr
Greetings
iz5tep

**Comment by martinling** [comment]
This would be a feature request for the SDR software you're using. The HackRF project just provides the hardware and the raw I/Q sample interface.

**Comment by iz5tep** [comment]
yes, that's exactly what I meant, I was referring to the software.
73

Il giorno gio 25 gen 2024 alle ore 15:57 Martin Ling <
***@***.***> ha scritto:

**Comment by martinling** [comment]
What software are you using? You should open this issue there.

**Comment by iz5tep** [comment]
software, SDRangel only dvb-s, both in rx and in tx with hackrf one
tnx

Il giorno gio 25 gen 2024 alle ore 18:15 Martin Ling <
***@***.***> ha scritto:

**Comment by martinling** [comment]
Then you should open an issue on the SDRAngel repository: https://github.com/f4exb/sdrangel/issues
