### ISSUE TITLE
Second Signal with hackrf_transfer

### ISSUE THREAD

**Issue by Klammraute** [greatscottgadgets/hackrf#1410]
### Have you read the HackRF [troubleshooting documentation](https://hackrf.readthedocs.io/en/latest/troubleshooting.html)?

yes

### What outcome were you hoping for?

a normal Replay of a Signal

### What outcome actually happened?

When I try to send a .raw file, an additional signal appears to the right of the normal signal, even though the settings and the audio file are the same as with SDRAngel. It doesn't modulate the signal as desired. Did I forget something in the hackrf_transfer command? 
![hackrf_fallFinal](https://github.com/greatscottgadgets/hackrf/assets/19589850/a6685969-9c6a-4300-b0a3-169d4413107e)

### What operating systems are you seeing the problem on?

Ubuntu Server

### What is the output of ```hackrf_info```?

hackrf_info version: unknown
libhackrf version: unknown (0.6)
Found HackRF
Index: 0
Serial number: 0000000000000000453c64c825655d8f
Board ID Number: 2 (HackRF One)
Firmware Version: 2017.02.1 (API:1.02)
Part ID Number: 0xa000cb3c 0x00644f5c

### Are you using any third-party software?

Hackrf Directly and SDRAngeln 

### Are you using any third-party hardware?

Normal Amateurradio Antenna

**Comment by martinling** [comment]
You have the wrong sample format. The input to `hackrf_transfer` should be signed 8-bit samples. The SDRAngel documentation says it takes 16-bit samples.

**Comment by Klammraute** [comment]
Hi, 

i have to correct me, the file i transmit with hackrf_transfer -t, i also recorded with hackrf_transfer -r, its a different file like in sdrangel

thank you

**Comment by martinling** [comment]
Using `hackrf_transfer -r` will record all signals within the received bandwidth, including the DC spike in the middle. You would need to process the data further to extract the signal of interest.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
