### ISSUE TITLE
osmocom-fft and gnuradio-companion python issue

### ISSUE THREAD

**Issue by davidwowa** [greatscottgadgets/hackrf#1421]
I try to start osmocom-fft or one flow in gnuradio-companion. Start with osmocom-fft following log:

> :~/Downloads/hackrf-2024.02.1/firmware-bin$ osmocom_fft 
> CPU Features: SSE2+ SSE4.1+ AVX+ FMA-
> Using avx for xtrxdsp_iq16_sc32
> Using avx for xtrxdsp_iq8_ic16
> Using avx for xtrxdsp_iq16_ic16i
> Using avx for xtrxdsp_iq8_ic8i
> Using avx for xtrxdsp_sc32i_iq16
> Using avx for xtrxdsp_iq8_sc32
> Using avx for xtrxdsp_iq8_sc32i
> Using avx for xtrxdsp_iq16_sc32i
> Using avx for xtrxdsp_sc32_iq16
> Using avx for xtrxdsp_ic16i_iq16
> gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.9.2
> built-in source types: file fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp xtrx 
> [INFO] [UHD] linux; GNU C++ version 13.2.0; Boost_108300; UHD_4.6.0.0+ds1-5+b2
> [ERROR] avahi_service_browser_new() failed: Bad state
> libusb: warning [libusb_exit] device 2.16 still referenced
> libusb: warning [libusb_exit] device 2.13 still referenced
> libusb: warning [libusb_exit] device 2.10 still referenced
> libusb: warning [libusb_exit] device 2.7 still referenced
> libusb: warning [libusb_exit] device 2.4 still referenced
> libusb: warning [libusb_exit] device 2.1 still referenced
> libusb: warning [libusb_exit] device 1.18 still referenced
> libusb: warning [libusb_exit] device 1.37 still referenced
> libusb: warning [libusb_exit] device 1.19 still referenced
> libusb: warning [libusb_exit] device 1.13 still referenced
> libusb: warning [libusb_exit] device 1.10 still referenced
> libusb: warning [libusb_exit] device 1.7 still referenced
> libusb: warning [libusb_exit] device 1.4 still referenced
> libusb: warning [libusb_exit] device 1.1 still referenced
> Using HackRF One with firmware 2024.02.1
> flowgraph :warning: Could not find port freq in:
> flowgraph :warning:   system
> flowgraph :warning:   bw
> flowgraph :warning:   freq
> flowgraph :warning:   in
Traceback (most recent call last):
>   File "/usr/bin/osmocom_fft", line 717, in <module>
>     main()
>   File "/usr/bin/osmocom_fft", line 693, in main
>     tb = app_top_block(qapp.arguments(), "osmocom Spectrum Browser")
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/bin/osmocom_fft", line 307, in __init__
>     self.msg_connect((self.scope, 'freq'), (self.freq, 'msg'))
>   File "/usr/local/lib/python3.11/dist-packages/gnuradio/gr/hier_block2.py", line 53, in wrapped
>     func(self, src.to_basic_block(), srcport, dst.to_basic_block(), dstport)
>   File "/usr/local/lib/python3.11/dist-packages/gnuradio/gr/hier_block2.py", line 147, in msg_connect
>     self.primitive_msg_connect(*args)
> ValueError: invalid msg port in connect() or disconnect()
> Speicherzugriffsfehler

And 

<img width="584" alt="image" src="https://github.com/greatscottgadgets/hackrf/assets/9664105/bf1f99f5-ea06-44ad-b26f-21c7aa569519">

### What are the steps to reproduce this?

Running commands 'osmocom-fft' or 'gnuradio-comanion'.

**Comment by martinling** [comment]
I don't see a HackRF issue here, your problem seems to be with your GNU Radio installation.
