### ISSUE TITLE
Sync hack rf one

### ISSUE THREAD

**Issue by AlMasz2837** [greatscottgadgets/hackrf#1427]
### What would you like to know?

Hi, hackrf one receives a rectangular pulse with a frequency of 10 MHz 3.3 V on CLK in, is it possible to reduce this frequency and apply, for example, a frequency of 1 kHz?
generation using an external source (signal generator)

**Comment by martinling** [comment]
To use a different CLKIN frequency you would need to make some modifications to the firmware. Currently it uses a fixed configuration of the Si5351 clock generator that works for 10MHz input. You would need to work out how to configure the Si5351 to operate with the input frequency you want instead, and then make the necessary changes to how the firmware configures it. I don't know whether it would work well with an input as low as 1kHz.
