### ISSUE TITLE
Hackrf_sweep error at ranges above 160mhz

### ISSUE THREAD

**Issue by Klammraute** [greatscottgadgets/hackrf#1428]
### What type of issue is this?

permanent - occurring repeatedly

### What issue are you facing?

Hello, when I use hackrf_sweep and display the CSV file with plottsweep, all the PNGs above a scan range of 160MHz are intersected with white lines. Is there any way to avoid this?

### What are the steps to reproduce this?

hackrf_sweep -f 140:300 -l 32 -g 48 -w 50000 -r test1.csv 
plotsweep test1.csv example.png --power-min -60 --power-max -15.0 --colormap magma
works perfectly 
![nolines](https://github.com/greatscottgadgets/hackrf/assets/19589850/844aef0b-66e8-4224-a248-448d5f6ef239)

but not over 160 mhz 
hackrf_sweep -f 140:310 -l 32 -g 48 -w 50000 -r test2.csv 
plotsweep test2.csv example2.png --power-min -60 --power-max -15.0 --colormap magma
![lineswhite](https://github.com/greatscottgadgets/hackrf/assets/19589850/8e58aab9-135e-466c-bf2b-e0ba9f25b77f)

**Comment by martinling** [comment]
This happens because the timestamp of the data can change midway through a sweep.

If you install the latest 2024.02.1 release, there is a new `-n` option to `hackrf_sweep`, which will use the same timestamp throughout one sweep, and that should eliminate this effect.

**Comment by Klammraute** [comment]
thank you, solved :3
