### ISSUE TITLE
Opera Cake

### ISSUE THREAD

**Issue by shugaj** [greatscottgadgets/hackrf#1437]
### Have you read the HackRF [documentation](https://hackrf.readthedocs.io/en/latest/)?

yes

### What outcome were you hoping for?

Hello, heed help.
Don't understand, how configure OperaCacke to 1x8 single switch.

### What outcome actually happened?

How to combine OperaCacke into an 8-port switch

### What operating systems are you seeing the problem on?

not operating system, it's hardware

### What is the output of ```hackrf_info```?

n/a

### Are you using any third-party software?

no

### Are you using any third-party hardware?

OperaCacke

**Comment by mossmann** [comment]
You can use primary port A0 as the single port that gets switched between eight secondary ports (A1-A4 and B1-B4). Then use one of the following commands to select the active port:
```
hackrf_operacake -a A1
hackrf_operacake -a A2
hackrf_operacake -a A3
hackrf_operacake -a A4
hackrf_operacake -a B1
hackrf_operacake -a B2
hackrf_operacake -a B3
hackrf_operacake -a B4
```
See https://hackrf.readthedocs.io/en/latest/opera_cake_port_configuration.html for command syntax.
