### ISSUE TITLE
Connot get into updating HRFh2+

### ISSUE THREAD

**Issue by RXANDR1** [greatscottgadgets/hackrf#1446]
### Have you read the HackRF [documentation](https://hackrf.readthedocs.io/en/latest/)?

yes

### What outcome were you hoping for?

To be able toupdate firmware

### What outcome actually happened?

no option, cannot intigrate w/PC.
Tried driver change,cannot seem to get update to go :-/

### What operating systems are you seeing the problem on?

Windows

### What is the output of ```hackrf_info```?

dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

DFU suffix CRC does not match
A valid DFU suffix will be required in a future dfu-util release!!!
Opening DFU capable USB device...
ID 1fc9:000c
Run-time device DFU version 0100
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 0100
Device returned transfer size 2048
Copying data from PC to DFU device
Download        [=========================] 100%        42564 bytes
Download done.
unable to read DFU status after completion
can't detach
Resetting USB to switch back to runtime mode

### Are you using any third-party software?

No

### Are you using any third-party hardware?

Which ever PortaPack

**Comment by straithe** [comment]
For support with Portapack please contact the company you purchased your device from.
