### ISSUE TITLE
Digitization of the signal

### ISSUE THREAD

**Issue by Sentos777** [greatscottgadgets/hackrf#1451]
### What would you like to know?

Hello everyone,

I am trying to find the code in the software that is responsible for sampling and digitizing data. Could you please let me know where to look? Also, I would like to know how many samples the ADC selects to restore the spectrum, and if it is possible to use the HackRF One to measure the absolute value or phase ratio of a signal, as with a VNA Nano.

Thank you for your help.

**Comment by Moji14** [comment]
There's no code for sampling and digitizing, these functions are done by the ADC, all you can do is control the ADC parameters via registers. Have a look on the MAX5864 to see if that can answer your questions. A VNA works differently to a radio receiver a VNA
consists of one or more generators and typically two coherent selective receivers for each test port.
