### ISSUE TITLE
osmocom_fft error:"AttributeError: 'gnuradio.qtgui.qtgui_python.freq_sink_c' object has no attribute 'pyqwidget'. Did you mean: 'qwidget'?

### ISSUE THREAD

**Issue by HZX0748** [greatscottgadgets/hackrf#1454]
### Have you read the HackRF [documentation](https://hackrf.readthedocs.io/en/latest/)?

yes

### What outcome were you hoping for?

successfully run osmocom_fft command and recieve siganl from my hackrf_one hardware and show Frequency domain diagram.

### What outcome actually happened?

It stops at this error: AttributeError: 'gnuradio.qtgui.qtgui_python.freq_sink_c' object has no attribute 'pyqwidget'. Did you mean: 'qwidget'?''  I try to fix it according to this [issue]( https://github.com/gnuradio/gnuradio/issues/5175). However downgrated GNURadio version did not fix the problem. I also try re-build gr-osmosdr and hackrf, but the errors remain unchanged.

log:
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
gr-osmosdr 0.2.0.0 (0.2.0) gnuradio 3.10.1.1
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy airspyhf soapy redpitaya freesrp 
[INFO] [UHD] linux; GNU C++ version 11.2.0; Boost_107400; UHD_4.1.0.5-3
libusb: warning [libusb_exit] device 4.1 still referenced
libusb: warning [libusb_exit] device 3.4 still referenced
libusb: warning [libusb_exit] device 3.3 still referenced
libusb: warning [libusb_exit] device 3.5 still referenced
libusb: warning [libusb_exit] device 3.2 still referenced
libusb: warning [libusb_exit] device 3.1 still referenced
libusb: warning [libusb_exit] device 2.1 still referenced
libusb: warning [libusb_exit] device 1.1 still referenced
Using HackRF One with firmware local-79baef7
Traceback (most recent call last):
  File "/usr/bin/osmocom_fft", line 714, in <module>
    main()
  File "/usr/bin/osmocom_fft", line 690, in main
    tb = app_top_block(qapp.arguments(), "osmocom Spectrum Browser")
  File "/usr/bin/osmocom_fft", line 297, in __init__
    self.scope_win = sip.wrapinstance(self.scope.pyqwidget(), Qt.QWidget)
AttributeError: 'gnuradio.qtgui.qtgui_python.freq_sink_c' object has no attribute 'pyqwidget'. Did you mean: 'qwidget'?
Segmentation fault (core dumped)

### What operating systems are you seeing the problem on?

Ubuntu 22.04 LTS

### What is the output of ```hackrf_info```?

hackrf_info
hackrf_info version: 2024.02.1+
libhackrf version: 2024.02.1+ (0.9)
Found HackRF
Index: 0
Serial number: 0000000000000000a41c61dc32879313
Board ID Number: 2 (HackRF One)
Firmware Version: local-79baef7 (API:1.03)
Part ID Number: 0xa000cb3c 0x00584765

### Are you using any third-party software?

GNURadio 3.10.1.1

### Are you using any third-party hardware?

no

**Comment by straithe** [comment]
You may not get the help you need here since it seems that your issue is not with HackRF, but the software you are using. For more assistance please refer to GNURadio's help forums and community for support.
