### ISSUE TITLE
hackrf_biast for Windows

### ISSUE THREAD

**Issue by Totoche95** [greatscottgadgets/hackrf#1455]
### What feature would you like to see and why?

Hello,
Is it possible to have a Windows version of hackrf_biast to activate bias tee ?

Cheers

**Comment by martinling** [comment]
Yes. You can always grab Windows builds from the latest CI run on this repository.

The most recent is here: https://github.com/greatscottgadgets/hackrf/actions/runs/8926611271/artifacts/1467694385
