### ISSUE TITLE
Replacement of TPS62410 Buck converter 

### ISSUE THREAD

**Issue by anxzik** [greatscottgadgets/hackrf#1463]
![20240623_025301](https://github.com/greatscottgadgets/hackrf/assets/103099778/7f5f87e6-2505-4943-9415-a900b77ddf40)
### Have you read the HackRF [documentation](https://hackrf.readthedocs.io/en/latest/)?

yes

### What outcome were you hoping for?

I have a unit from 2014, when plugged in, it is recognized after a few moments its starts flickering LEDs and looses connectivity,  the chip in the corner gets extremely hot. using Kicad iv found the chip to be the TI Buck converter, yet the one on the unit is marked CAT 081 A5JK .. I just wanted to confirm that https://www.ti.com/product/TPS62410 is the correct chip  or if there had been a revision what part should i order?

### What outcome actually happened?

nothing yet seeking further guidance in repair of PCB

### What operating systems are you seeing the problem on?

Linux, 
![20240623_023821](https://github.com/greatscottgadgets/hackrf/assets/103099778/0f76bb5b-da68-48c3-aec1-5c9a8b09668f)
![20240623_023959](https://github.com/greatscottgadgets/hackrf/assets/103099778/1376c6fc-a336-4429-b4b4-059db3966da3)
![20240623_025235](https://github.com/greatscottgadgets/hackrf/assets/103099778/cd3a0be3-d69e-4c39-a515-85f3381d00b9)
![Uploading 20240623_025301.jpg…]()
Win 10 - 11

### What is the output of ```hackrf_info```?

n/a

### Are you using any third-party software?

No

### Are you using any third-party hardware?

Hack RF was Originally paired with Portapack

**Comment by straithe** [comment]
Can you please add a picture of your HackRF to this issue?

**Comment by martinling** [comment]
TPS62410 is the correct replacement for U21, regardless of board revision.

However, you have other issues: one of the capacitors next to U21 is visibly cracked:

![image](https://github.com/greatscottgadgets/hackrf/assets/673823/ed2977a0-35ce-4c2e-b21c-25e372642d92)

I suggest you start by checking that whole area for other damaged components.

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
