### ISSUE TITLE
SD Card Issues with Portapack H2

### ISSUE THREAD

**Issue by Mike511986** [greatscottgadgets/hackrf#1468]
### What would you like to know?

I recently bought a Portapack H2 and it didn't come with an SD card. I bought a blank one, formatted it as FAT32 and uploaded the Mayhem firmware files onto it. It seems that the H2 will not "see" any of the files on the card and says there are none loaded. When I tested the SD card using the Debug feature on the H2, it gave me a message saying, "FAIL: FILE OPEN WRITE".

**Comment by straithe** [comment]
Portapack is not a Great Scott Gadgets product. You will have to contact the person you ordered the device from in order to get support for Portapack.
