### ISSUE TITLE
lesson1 not running

### ISSUE THREAD

**Issue by whaleshark88** [greatscottgadgets/hackrf#1477]
### Have you read the HackRF [documentation](https://hackrf.readthedocs.io/en/latest/)?

yes

### What outcome were you hoping for?

Hi I am new to hackrf one and gnu radio, I am following the flowchart on greatscottgadgets lesson1 to receive fm siganls using the hackrf one

### What outcome actually happened?

it does not run.

### What operating systems are you seeing the problem on?

windows 10
![test1](https://github.com/user-attachments/assets/5efe2d0f-7d60-43e9-b2b0-278eb771d960)

### What is the output of ```hackrf_info```?

  File "C:\Users\Dell XPS 9550\Documents\test1.py", line 167, in __init__
    self.osmosdr_source_0 = osmosdr.source(
                            ^^^^^^^^^^^^^^^
RuntimeError: Wrong device arguments specified. Missing nchan?

>>> Done (return code 1)

### Are you using any third-party software?

gnu radio

### Are you using any third-party hardware?

no

**Comment by miek** [comment]
Can you post a picture of the properties window of the osmocom Source block? I think the issue is that the device properties field is set wrong, it should be just `hackrf=0` with no spaces or other characters.
