### ISSUE TITLE
Convert sampling rate of .C16 file

### ISSUE THREAD

**Issue by dudelaksdfjlkaz0102** [greatscottgadgets/hackrf#1490]
### What would you like to know?

I have an IQ file recorded at 250kHz sampling rate created with HackRF Mayhem v1.4 firmware. I'm unable to record the signal again. I need to convert to 2MHz sampling rate allowing replay with latest HackRF Tool & Mayhem firmware. Can you tell me the names of software that will convert and where I can find them?

**Comment by mossmann** [comment]
In the past I have used [csdr](https://github.com/ha7ilm/csdr) for this, but it appears to no longer be maintained. I recommend building a flowgraph in GNU Radio.
