### ISSUE TITLE
Brand new HackRF One out of box failure #1480 - Still not transmitting any signal after receiving back from Canada Robotix

### ISSUE THREAD

**Issue by Manishaalk** [greatscottgadgets/hackrf#1496]
### Have you read the HackRF [documentation](https://hackrf.readthedocs.io/en/latest/)?

yes

### What outcome were you hoping for?

Transmit AIS signal

### What outcome actually happened?

When run the GNU radio to supply it the AIS messages at center frequency 162Mhz, No signal transmitted by HackRF One.

### What operating systems are you seeing the problem on?

Windows

### What is the output of ```hackrf_info```?

(base) C:\Users\ManishaDesai> hackrf_info
hackrf_info version: 2024.02.1
libhackrf version: 2024.02.1 (0.9)
Found HackRF
Index: 0
Serial number: 000000000000000066a062dc276b579f
Board ID Number: 2 (HackRF One)
Firmware Version: 2024.02.1 (API:1.08)
Part ID Number: 0xa000cb3c 0x005d475c
Hardware Revision: r10
Hardware appears to have been manufactured by Great Scott Gadgets.
Hardware supported by installed firmware:
    HackRF One

### Are you using any third-party software?

GNU Radio

### Are you using any third-party hardware?

No

**Comment by straithe** [comment]
Closed as duplicate.
