### ISSUE TITLE
Firmware should stop TX/RX when communication is lost

### ISSUE THREAD

**Issue by kpreid** [greatscottgadgets/hackrf#180]
Feature request:

If the host process which is controlling the HackRF is abruptly terminated, the HackRF remains in TX or RX mode. It would be nice if the firmware would instead recognize this condition and shut off the transmitter/receiver.

I'm not familiar enough with USB to know whether this is a detectable event (analogous to a lost TCP connection) or would require timeout logic (e.g. not receiving any TX data packets or other keepalive).

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5295633/buckets/26082705/todos/4597360884) by [Unito](https://www.unito.io)

**Comment by KC5CQW** [comment]
User adjustable "watchdog" timer is especially for TX is needed for compliance with various communications authorities. Not to mention, equipment/DUT safety.

**Comment by rroff** [comment]
Hey,

Have you seen that latest movie? I don't know what all the fuss is about. Before you watch it read a review here <http://tusindutro.peterbillingsley.org/aecpdyn>

See you soon, rroff@roff.us

**Comment by dominicgs** [comment]
For TX I plan to keep track of the freshness of the buffers to be transmitted. There's no sense in transmitting buffers that have already been transmitted (not in our current usage model), so I'll reset to idle if that happens.

I'm fairly sure it could work that way for RX, but I don't know if total failure is the answer for a slower than expected USB connection.  I think it's a fair thing to do, but I worry that it will break some things in subtle ways.
