### ISSUE TITLE
Feature Request: use all the 10 bits of the DAC 

### ISSUE THREAD

**Issue by Paco93** [greatscottgadgets/hackrf#300]
Sorry if this is the wrong place for asking it.
For certain applications 8 bits DAC is quite limiting. As the DACs in MAX5864 are10 bits wide it would be great to have an USB connection mode transferring 16 bits wide samples (accepting a decrease in the maximum usable  sample rate) in addition to the defaul mode transerring 8 bits samples . 
Thanks

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5295633/buckets/26082705/todos/4597374603) by [Unito](https://www.unito.io)

**Comment by mossmann** [comment]
This is theoretically possible, but it would require a great deal of work.  In my opinion, it would provide very little benefit.  It is already possible to simulate higher resolution at lower sample rates by using a high sample rate with a low bandwidth reconstruction filter (e.g. hackrf_transfer -s 20000000 -b 1750000).

Can you describe a specific example of an application that would benefit greatly from 10 bit TX resolution?

**Comment by Paco93** [comment]
My application is in a traffic emulator for random spread spectrum signals  In this application i can generate a large number of cofrequency spread spectrum signals with the number of signals which can change with time to emulate random variabiliti of traffic

**Comment by Paco93** [comment]
Sorry i closed inadvertently the message. To conclude I agree that my case is a fringe case. Feel free to close the issue if you think it is not Worth the effort and thanks for the good work you are done.

**Comment by Radiomix2000** [comment]
> by using a high sample rate with a low bandwidth reconstruction filter (e.g. hackrf_transfer -s 20000000 -b 1750000
Is this trick possible in gnuradio? 
I also think it's great idea to have 10 bits onboard for more precise accuracy. For some modulations is not necessary to have 8 bit.

**Comment by mossmann** [comment]
I'm happy to leave this issue open in case anyone wants to work on it, but I don't plan to spend time on it myself.

**Comment by mossmann** [comment]
I'm closing this issue because I no longer believe it to be theoretically possible without a complete reimplementation of our CPLD and SGPIO solutions, removing some other functionality that we rely on. A custom solution for a particular use case may be possible, but it would be external to this repository.
