### ISSUE TITLE
Add opera cake photos and/or diagrams to documentation

### ISSUE THREAD

**Issue by dominicgs** [greatscottgadgets/hackrf#532]
A picture is worth 1000 words and I often struggle to write 100.  A picture or diagram of opera cake on the wiki page will help to make sure we're all on the same page when discussing the hardware.

Annotations:

* Ports
* Headers
* Address jumpers

**Comment by straithe** [comment]
Add annotated picture of Opera Cake to the top of https://hackrf.readthedocs.io/en/latest/opera_cake.html
