### ISSUE TITLE
hackrf_info --verbose

### ISSUE THREAD

**Issue by dominicgs** [greatscottgadgets/hackrf#578]
Add a verbose option to `hackrf_info` so that we can retrieve the state of the radio and other firmware settings.  This will aid in debugging issues.

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5295633/buckets/26082705/todos/4597414923) by [Unito](https://www.unito.io)

**Comment by martinling** [comment]
Duplicate of #452.
