### ISSUE TITLE
Streaming is started before RF path is fully set up

### ISSUE THREAD

**Issue by miek** [greatscottgadgets/hackrf#706]
This leads to some spurious data at the beginning of an RX stream (possibly TX too).

(Split from some discussion in #703)

┆Issue is synchronized with this [Basecamp todo](https://3.basecamp.com/5295633/buckets/26082705/todos/4597431483) by [Unito](https://www.unito.io)

**Comment by martinling** [comment]
I don't think there's any way this can happen now after the changes in #982 and #1045.
