### ISSUE TITLE
Sniffing multiple BL&BLE packets at the same time with HackRF One?

### ISSUE THREAD

**Issue by alimertcoskun** [greatscottgadgets/hackrf#709]
Hi,

I want to detect BL or Bluetooth packets with HackRF One. As you know, HackrfOne measure 20MHz bandwidth  on 1MHz to 6GHz operating frequency also contain BL,BLE frequencies. I wonder, Can I get BL,BLE packages from 20 channels at the same time, is it possible? For example, can I sniff packages between 2.402GHz-2.2.422 GHz at the same time? Can you help me with this?

Thanks from now!

**Comment by mossmann** [comment]
Yes, it is certainly possible to receive Bluetooth Classic and Low Energy packets on up to 20 channels simultaneously with HackRF One, but I don't know of any software that currently implements this capability. Our old [gr-bluetooth](https://github.com/greatscottgadgets/gr-bluetooth) project has implemented multi-channel monitoring of Bluetooth Classic but not LE.
