### ISSUE TITLE
Clock Locking with An RPi to combat RPi/Gnuradio 2-clock problem

### ISSUE THREAD

**Issue by diverd999** [greatscottgadgets/hackrf#757]
Hi All,

I've developed a receiver system that's working fine with an analog radio & I'd like to convert to an SDR. The analog radio has a fixed delay & that's critical for me as I process the audio. I've experimented with an rtl-sdr & an RPi4. Everything  looks good except the 2-clock problem. Since the SDR has a clock & so does the Pi, the delay through the receiver is not constant but drifts as the 2 clock sources drift. Occasionally it hops too as the internal audio fifo resets.

I can generate a reasonable 10MHz clock from the RPi through a GPIO pin. If I feed that to the HackRF One, everything should be locked up & the audio from the RPi should then not drift as the rf clock & the audio clocks are both synthesised come from the same crystal on the RPi................... That's the theory.

Has anyone else tried this or have any comments? Am I missing anything?

Thanks, Dave

**Comment by straithe** [comment]
Yes, in theory! Our team is not familiar with the internals of the RPi4 though, so we leave that experimentation to you. Good luck.
