### ISSUE TITLE
HackRF One version??

### ISSUE THREAD

**Issue by josooik** [greatscottgadgets/hackrf#880]
What difference does the HackRF One 2014 version and the HackRF One 2020 version make?
![캡처](https://user-images.githubusercontent.com/7031071/115910968-7471ad00-a4a8-11eb-9963-76d274f9af70.PNG)
![115902349-50f53500-a49d-11eb-9c24-42491f90336f](https://user-images.githubusercontent.com/7031071/115910974-75a2da00-a4a8-11eb-812d-a791c9f38a46.jpg)

**Comment by ellisdee110** [comment]
I can't find out what these chinese vendors mean either. Anyone know?? i assume either marketing or they couldn't get exact components anymore and used what was available. I ordered a "2020" to get a closer look.

**Comment by straithe** [comment]
The HackRF hardware versions that have been manufactured by Great Scott Gadgets, and the changes between them, are listed here: https://hackrf.readthedocs.io/en/latest/list_of_hardware_revisions.html 

We do not have intimate knowledge of the hardware produced by other manufacturers and whether they line up with any of our hardware revisions. I'm closing this issue as I don't have any other knowledge to provide. You could try contacting your reseller for more information.
