### ISSUE TITLE
IQ difference with two HackRF One

### ISSUE THREAD

**Issue by Michel0001** [greatscottgadgets/hackrf#892]
Hello, I have two hackrf one with 2017.02.1 software, one of which has ghost frequencies opposite the center frequency.

The difference I may have noticed is an abnormal IQ distribution (Red).

![Quadrature HackRF One](https://user-images.githubusercontent.com/38522910/119740727-afd71100-be84-11eb-9dc8-4f53c07323ee.PNG)

Is it a hardware or software problem? What would be at the origin of this abnormal IQ distribution?
Thanks.

**Comment by straithe** [comment]
Do you still observe this problem after updating to [v2021.03.01](https://github.com/mossmann/hackrf/releases/tag/v2021.03.1)?

**Comment by Michel0001** [comment]
I've upgrade firmware to v2021.03.01 and it's the same.
I think it may come from a bad reference for the ADC

![image](https://user-images.githubusercontent.com/38522910/120459763-c7d4f600-c398-11eb-846d-92232aea294f.png)

**Comment by straithe** [comment]
Can you please post the flow graph that you used to generate your initial set of graphs with both the red and the blue plotted?

**Comment by Michel0001** [comment]
![hackrf_test](https://user-images.githubusercontent.com/38522910/122165714-e5b25880-ce78-11eb-9aa0-b1b3429f85df.png)
Hello, I think there is a difference in the components. Where can I find the test points  ​​and measured values ?

**Comment by vladisslav2011** [comment]
> Is it a hardware or software problem?

Looks like hardware problem. Solder joint on SGPIO2 or broken resistor...

**Comment by Michel0001** [comment]
Thanks for the answer, I checked between BANK2F3M9 (74) and SGPIO2 (62) and I have the R89 resistor of 39 Ohms.

**Comment by vladisslav2011** [comment]
Measure the resistor to check, that it is not broken. Check both BANK2F3M9 (74) and SGPIO2 (62) for connection to VCC. There should be either connection, that should not exist or missing connection, that should exist. 
Your constellation is showing, that there should be connection between BANK2F3M9 (74) and VCC or SGPIO2 (62) and VCC maybe through surrounding pins. Or broken resistor/traces/bad soldering between BANK2F3M9 (74) and SGPIO2 (62) in case, there is pull-up enabled on SGPIO2 .

**Comment by straithe** [comment]
@Michel0001 did you try the suggestion from @vladisslav2011 ?

**Comment by straithe** [comment]
I'm closing this as there hasn't been a response in over 30 days. Please re-open this issue or open a new one if you still need assistance.
