### ISSUE TITLE
`hackrf_transfer` reports bogus transmit amplitude

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/hackrf#902]
### Steps to reproduce
`hackrf_transfer -t /dev/zero` or `hackrf_transfer -c 127`

### Expected behaviour
Amplitude, if reported at all, should be computed from the samples sent over USB.

### Actual behaviour
```
19.9 MiB / 1.000 sec = 19.9 MiB/second, amplitude -inf dBfs
19.9 MiB / 1.000 sec = 19.9 MiB/second, amplitude -inf dBfs
19.9 MiB / 1.000 sec = 19.9 MiB/second, amplitude -inf dBfs
```

**Comment by palpicture** [comment]
any solution ? i have the same issue

**Comment by ardyitjen** [comment]
is there any update? i got sampe problem with portapack h2
