### ISSUE TITLE
Reorganize libhackrf API documentation

### ISSUE THREAD

**Issue by straithe** [greatscottgadgets/hackrf#905]
Use functions as headings, remove existing headings, fill out contents.

**Comment by miek** [comment]
It might be worth setting up Doxygen (or similar) to generate API docs from the source? I think it would make it easier to keep everything in sync as the API changes. There are some plugins that integrate it with sphinx/readthedocs, e.g: https://breathe.readthedocs.io/en/latest/index.html

**Comment by mossmann** [comment]
This looks like a good guide: https://devblogs.microsoft.com/cppblog/clear-functional-c-documentation-with-sphinx-breathe-doxygen-cmake/
