### ISSUE TITLE
hackrf_spiflash_erase() failed: Input/Output Error (-1000)

### ISSUE THREAD

**Issue by KyleKotowick** [greatscottgadgets/hackrf#939]
### Steps to reproduce
1. Build `hackrf` 2021.03.01 [from source](https://hackrf.readthedocs.io/en/latest/operating_system_tips.html#building-hackrf-tools-from-source)
2. Run `hackrf_spiflash -w hackrf_one_usb.bin`

### Expected behaviour
It flashes the new firmware to the device.

### Actual behaviour
It returns the following output:
```
File size 35444 bytes.
Checking target device compatibility
Erasing SPI flash.
hackrf_spiflash_erase() failed: Input/Output Error (-1000)
```

### Version information
**Operating system**:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```

**hackrf_info output:**
```
hackrf_info version: 2021.03.1
libhackrf version: 2021.03.1 (0.6)
Found HackRF
Index: 0
Serial number: 0000000000000000909864c8357595cf
Board ID Number: 2 (HackRF One)
Firmware Version: git-31b83ef (API:1.03)
Part ID Number: 0xa000cb3c 0x004b435c
```

**Comment by miek** [comment]
Could you paste the output of `hackrf_spiflash -s -v`?

**Comment by KyleKotowick** [comment]
`hackrf_spiflash -s -v`
```
SRP0    1
SEC     1
TB      1
BP      7
WEL     0
Busy    0
SUS     0
CMP     1
LB      0
Res     0
QE      1
SRP1    0

```

**Comment by miek** [comment]
What happens if you run `hackrf_spiflash -c -R` and then `hackrf_spiflash -s -v`?

**Comment by KyleKotowick** [comment]
Running `hackrf_spiflash -c -R` (both with and without `sudo`) returns the following error:
```
hackrf_spiflash_clear_status() failed: Input/Output Error (-1000)
```

**Comment by miek** [comment]
Ah OK, I think I see what's going on now.

Older firmware had a bug where it would hang in `w25q80bv_write_enable` if any of the flash write protect bits are set, and that's what causes the "Input/Output" error. This was fixed in a357a7b1f05e25c5991188699a789b6e2aa8bb2e.

So, if you follow the instructions here: https://hackrf.readthedocs.io/en/latest/updating_firmware.html#only-if-necessary-recovering-the-spi-flash-firmware to do a DFU boot first then that will load the new firmware into RAM, allow the protect bits to be cleared and then programming should work via `hackrf_spiflash`

**Comment by KyleKotowick** [comment]
When running the command on that page:
`dfu-util --device 1fc9:000c --alt 0 --download hackrf_one_usb.dfu`
I get the error:
```
dfu-util: DFU suffix CRC does not match
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: No DFU capable USB device available
```

I figured that the device ID (`1fc9:000c`) in the command might be a placeholder so I tried `dfu-util -l`, and got this output:
```
dfu-util 0.9
```

So no devices are listed. Seems like `dfu-util` isn't recognizing the HackRF?

I see there's an alternative method on that link you posted:
`make -e BOARD=HACKRF_ONE RUN_FROM=RAM program`

Although this is unclear: what should `program` be in this case?
```

**Comment by miek** [comment]
> **EDIT:**
> I'm seeing now that the board has to be booted into DFU mode by pressing the DFU button. The device is on a remote computer that I have no access to; is there any other way to accomplish this?

Unfortunately no, the only way to get into DFU mode is with the button.

> I see there's an alternative method on that link you posted:
> `make -e BOARD=HACKRF_ONE RUN_FROM=RAM program`
> 
> Although this is unclear: what should `program` be in this case?

It's just `program` verbatim - it doesn't need to be replaced with anything. However, that command is only for building from source and then it uses dfu-util after building, so the HackRF still needs to be in DFU mode first.

**Comment by straithe** [comment]
I'm going to close this as there hasn't been a response in a while, but please re-open this issue or open a new one if you still need assistance.
