### ISSUE TITLE
HackRF not connecting via USB

### ISSUE THREAD

**Issue by kaos713** [greatscottgadgets/hackrf#946]
Hi, I tried plugging in my HackRF for the first time in a while and it's not connecting at all. Hoping someone can point me in the right direction.

### Steps to reproduce
Plug in HackRF One using USB.

### Expected behaviour
USB/RX/TX lights illuminate.

### Actual behaviour
3V3 and 1V8 indicators illuminates green. RF indicator illuminates red. USB, TX and RX indicators do not illuminate.

### Version information
**Operating system**: Ubuntu 20.04.3

I checked these issues:
https://github.com/mossmann/hackrf/issues/456
https://github.com/mossmann/hackrf/issues/569

I ran 'lsusb': HackRF is not in the list.
I ran 'hackrf_info': 'No HackRF boards found.'

I booted into DFU Mode (by holding DFU button and pressing reset), no change.
I've tried multiple USB cables, USB ports, and computers, no change.

I also ran dmesg -T --follow and got the following output when I plugged in the HackRF:
[Sun Sep  5 12:25:58 2021] usb 2-1.1: new full-speed USB device number 53 using ehci-pci
[Sun Sep  5 12:25:58 2021] usb 2-1.1: device descriptor read/64, error -32
[Sun Sep  5 12:25:58 2021] usb 2-1.1: device descriptor read/64, error -32
[Sun Sep  5 12:25:58 2021] usb 2-1.1: new full-speed USB device number 54 using ehci-pci
[Sun Sep  5 12:25:58 2021] usb 2-1.1: device descriptor read/64, error -32
[Sun Sep  5 12:25:59 2021] usb 2-1.1: device descriptor read/64, error -32
[Sun Sep  5 12:25:59 2021] usb 2-1-port1: attempt power cycle
[Sun Sep  5 12:25:59 2021] usb 2-1.1: new full-speed USB device number 55 using ehci-pci
[Sun Sep  5 12:26:00 2021] usb 2-1.1: device not accepting address 55, error -32
[Sun Sep  5 12:26:00 2021] usb 2-1.1: new full-speed USB device number 56 using ehci-pci
[Sun Sep  5 12:26:00 2021] usb 2-1.1: device not accepting address 56, error -32
[Sun Sep  5 12:26:00 2021] usb 2-1-port1: unable to enumerate USB device

**Comment by straithe** [comment]
What OS are you using? Are you trying to use your HackRF on a bareboard machine or in a VM?

**Comment by kaos713** [comment]
> What OS are you using? Are you trying to use your HackRF on a bareboard machine or in a VM?

I'm have a fresh install of Ubuntu running on a laptop, not a VM.

**Comment by straithe** [comment]
Are you using the HackRF on its own, or are you using it with a Portapack?

**Comment by kaos713** [comment]
> Are you using the HackRF on its own, or are you using it with a Portapack?

Yup just on its own.

**Comment by straithe** [comment]
Have you tried DFU mode?

**Comment by kaos713** [comment]
> Have you tried DFU mode?

Yes. I tried booting before and after plugging it in via USB but it still doesn't connect (no USB lights flash and Ubuntu reports 'unable to enumerate USB device'.

**Comment by straithe** [comment]
Can you add a picture of your HackRF here?

**Comment by nxnjz** [comment]
Had a similar issue with an R9, solved it by plugging into a USB 2.0 port instead of a 3.0.
