### ISSUE TITLE
Valid range of width for hackrf_sweep?

### ISSUE THREAD

**Issue by egberts** [greatscottgadgets/hackrf#951]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Able to error out if the width is outside of (unknown) spec while using hackrf_sweep utility. 

### Actual behaviour
Unknown

### Version information
*
Documentation

### Output
Documentation shows valid range of width. 
```

**Comment by mossmann** [comment]
There are error messages that appear when the valid bin width (-n) range is exceeded, but these have some bugs. Additionally it would be good to add the valid range to the help text.
