### ISSUE TITLE
Official Portapack H1/ Hack RF not transmitting

### ISSUE THREAD

**Issue by Mopar44084** [greatscottgadgets/hackrf#972]
### Steps to reproduce
1.capture FM radio frequency
2.Replay radio frequency on same frequency or different
3.test sound output

### Expected behaviour
Transmit sound/music/voice

### Actual behaviour
Transmits without playing anything, like someone just keys mic 

### Version information
Mayhem 1.4.0

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by Mopar44084** [comment]
I will get some pics later, I have captured FM freq with wide band width, tested with HamPi os on RPI 3B+ using a RTLsdr (it's just a thin line) I also tested it with Baofeng uv-5r, a regular FM radio and my cell phone. It's just sounds like seone keys mic without transmitting.

**Comment by Mopar44084** [comment]
I was told by a member of greatscott gadgets to run a command from osmocom /gnu radio package to hear a tone at 433mhz:

osmocom_siggen_nogui -s 20M -f 433M --sine -x 1000

I was able to hear a constant tone on 433 mhz using beofeng uv-5r

I then rebooted portapack and tried to capture a wireless doorbell signal at 433.950 with no luck

**Comment by Mopar44084** [comment]
I haven't heard back from anyone?Anymore ideas?I did hear a tone when running that commandOn Oct 27, 2021 2:17 PM, Michael Ossmann ***@***.***> wrote:
Can you please try testing transmission in "hackrf mode" (as a USB peripheral with a host computer)? I recommend using osmocom_siggen_nogui for this. It is part of the gr-osmosdr package. You can transmit a 1 kHz test tone with:
osmocom_siggen_nogui -s 20M -f 433M --sine -x 1000

You should be able to hear the tone by tuning your handheld radio to 433 MHz (or whatever frequency you specify in the command).

**Comment by straithe** [comment]
Well, since the tone is playing it looks like the HackRF is working as expected when transmitting, which addresses the original issue you opened this thread with and confirms no TX issue.

Trying to capture a wireless doorbell signal is a completely different issue as it is RX and not TX. Unfortunately I have no experience using a raspberry pi or HamPi OS with a HackRF. I can let you know that other people have had trouble with raspberry pi and HackRF as the raspberry pi doesn't necessarily have the throughput required for how much data HackRF collects. Do you have a baremetal Ubuntu machine that you could hook HackRF up to instead?

**Comment by Mopar44084** [comment]
I do, it's Ubuntu 16.04- skywave Linux. I don't think I have all the dependency to install the program. Im Originally using it with the original portapack H1 On Nov 3, 2021 3:28 PM, Straithe ***@***.***> wrote:
Well, since the tone is playing it looks like the HackRF is working as expected when transmitting, which addresses the original issue you opened this thread with and confirms no TX issue.
Trying to capture a wireless doorbell signal is a completely different issue as it is RX and not TX. Unfortunately I have no experience using a raspberry pi or HamPi OS with a HackRF. I can let you know that other people have had trouble with raspberry pi and HackRF as the raspberry pi doesn't necessarily have the throughput required for how much data HackRF collects. Do you have a baremetal Ubuntu machine that you could hook HackRF up to instead?

**Comment by straithe** [comment]
To confirm that your HackRF receives properly, I suggest removing it from the Portapack, updating the firmware to the latest HackRF firmware, opening GQRX, and offset tuning GQRX to the frequency you are looking for.

**Comment by Mopar44084** [comment]
Would this error cause a problem? 
I'm Running Windows 10
![IMG_20211103_212800415_HDR](https://user-images.githubusercontent.com/86167080/140256027-0e1ffef4-22d2-4268-a8f0-e536fc55d2af.jpg)

**Comment by straithe** [comment]
What you are seeing shouldn't cause a problem.

Since your new goal seems to be trying to replay I suggest watching the [SDR video series](https://greatscottgadgets.com/sdr/) we provide. Video 11 in particular should be of good value to you.

**Comment by Mopar44084** [comment]
The Portapack H1 / Hackrf one is fixed!
Needed to update the CPLD on the hackrf

**Comment by straithe** [comment]
Thank you for the update! I'm very happy to hear you found a solution.
