### ISSUE TITLE
RF amplifier can be damaged

### ISSUE THREAD

**Issue by mossmann** [greatscottgadgets/hackrf#974]
The RF receive amplifier (U13, part number MGA-81563-TR1G) on HackRF One seems to be damaged in the field more than any other component. This has been known for a long time; some tips for avoiding damage may be found in this video:
https://greatscottgadgets.com/sdr/5/

As far as we know, damage does not occur without exceeding the -5 dBm limit documented here:
https://hackrf.readthedocs.io/en/latest/hackrf_one.html#receive-power

However, it is possible to exceed that limit by operating a HackRF One in close proximity to a higher power radio transmitter, something that many users would like to be able to do safely. Regardless of whether or not damaged units have been subjected to power levels exceeding the maximum specification, we would like to characterize the conditions under which the RF amplifier may be damaged and reproduce the failure in the lab.

Less frequently we have seen damage to the TX RF amplifier (U25, same part number), and we are interested in characterizing that failure as well.

Diagnosis of either failure is straightforward: If you enable a working amplifier, the power level should rise. If you enable a damaged amplifier, the power level drops instead.

If you have experienced this failure and have some idea of how it happened, please comment with any information that could help us reproduce the condition.

**Comment by mautas** [comment]
After receiving some MGA-81563 sparece, today I replaced blown U25 (Tx LNA) on my HackRF One (Original Rx LNA is still good).

I don't know how and when original U25 was blown.

After replacing the part I connected HackRF One to this RF Power Meter with a -30 dB attenuator. (https://www.passion-radio.com/swr-power-meter/rf-power8000-926.html) and started testing ouput at various amateur radio frequencies:

7000 khz
28000 khz
146 MHz
440 Mhz

These tests where performed with Hack RF One and a Portapack H2+ with Mayhem FW powered from my notebook USB Port. After a while I wanted to make some tests using SDRAngel and set the device to HackRF "native" mode from the portapack.

Regretably I cannot tell exactly when, but while doing some more tests switching on and off the Tx LNA in 28 MHz and 146 MHz things started to go weird with HackRF One kind of resetting... As everything was working OK before it took me some minutes to figure out this happened when I turned on Tx with the LNA on... as you may be guessing, the new LNA just replaced a couple of hours ago was blown and it seems to have ended up in some kind of short circuit that makes the whole board reset.

All I can say is that all the time everythig was correclty tied to my wattmeter. Even though this did not prevent the LNA blowing up while doing "legitimate" stuff (ie. not doing nothing normal device configuration prevents from doing). May be it was just bad luck and the new LNA was not a good part. I replaced it again, just checked out it was working on 7000 kHz and 146 MHz, turned it off and I don't think I will be enabling anytime soon.

As a ham radio enthusiast I absolutely love HackRF One but this whole MGA-81563 issue looks like a really really weak point. I regret not being able to offer much more details for what happened today besides saying that this happened without any operation error or misconsideration from me, just my HackRF One tied to my wattmeter and operating it withing its normal limits.

**Comment by mautas** [comment]
> After replacing the part I connected HackRF One to this RF Power Meter with a -30 dB attenuator. (https://www.passion-radio.com/swr-power-meter/rf-power8000-926.html) and started testing ouput at various amateur radio frequencies:
> 
> 7000 khz 28000 khz 146 MHz 440 Mhz
> 
> (yes, all in the amateur bands)

Tonight a friend of mine that gave a look to the MGA-81563 datasheet directed my attention to the fact that this IC range of operation starts at 100 MHz (0.1 GHz). May be this is not critical for Rx operation where power magnitudes might be low enough not to cause damage but using it for Tx is a whole different situation.

I think HackRF Firmware should prevent enabling the Tx MGA-81563 below 100 MHz since in my experiencie this might be a situation where you will probably will end with a burnt Tx amplifier. Even though I am not very sure if the chip went bad in the 10 meter band or the 2 meter band, now I am prone to think this happened while doing tests at 28 MHz. Perhaps people at GSG could do some tests to reproduce this situation and check out if operating this IC for Tx below 100 MHz is safe. 

Meanwhile I would recommend not enabling this stage for Tx below 100 MHz minimum specified frequency for the IC.

**Comment by mossmann** [comment]
> I _suspect_ it might have died at Toorcamp 2016 when I tried to hook it up to a sketchy 1.5W PA from eBay, although I'm not exactly sure what might have caused that. It looks like the input to the amp is AC-coupled through a cap. I could send you both the amp and the HackRF for analysis if you'd like.

Thank you for the offer! We will follow up with you out of band about shipping.

**Comment by mossmann** [comment]
> Meanwhile I would recommend not enabling this stage for Tx below 100 MHz minimum specified frequency for the IC.

That's an interesting suggestion. Thank you! The data sheet does not specify a frequency limit in its absolute maximum ratings, but we will do some testing.

**Comment by mautas** [comment]
> > Meanwhile I would recommend not enabling this stage for Tx below 100 MHz minimum specified frequency for the IC.
> 
> That's an interesting suggestion. Thank you! The data sheet does not specify a frequency limit in its absolute maximum ratings, but we will do some testing.

The datasheet title goes

MGA-81563
0.1– 6 GHz 3 V, 14 dBm Amplifier
Data Sheet

and
Introduction
This high performance GaAs
MMIC amplifier was developed for
commercial wireless applications
**from 100 MHz** to 6 GHz.

So, I guess operating this below 100 MHz puts us in uncharted territory

**Comment by eegan** [comment]
Reviewing the data sheet, indeed the amplifier may not have been characterized below 100MHz, but there is no reason to think it will suddenly stop working below this point.

It does look as if its gain might be a bit higher sub-100MHz, as well as its noise figure, if you extrapolate from the provided curves.

**Comment by Mclute0** [comment]
maybe a silly comment, but if LNA MICs are blowing up and I was forced to choose a replacement I would look at maybe more advanced ICs with better E protection built in and a wider range, like the LVA-123+ as an example. 

Yea, it costs single digit multiples of MGA-81563-TR1G, but hey it's for my use. An extra $8 would be worth it.

I would also look at maybe socketizing my LNA MICs so I can quickly change them out; you can do wonders with 3D printers these days. 

I know it is not as easy as I make it out....

drink!

McLute0

**Comment by electrical-pro** [comment]
Today my RX MGA-81563 died (short circuit). I don't know at which point it failed, prior to this I was using Hack RF with LNB, but MGA-81563 was off, so maybe it is unrelated. Already replaced with a new one, so everything is back to normal.
A long time ago my TX MGA-81563 died too, also exact moment is unknown (prior to that I was experimenting with an external amplifier connected to Hack RF).
After the first failure, I bought 10pcs MGA-81563, I still have 8 of them left, I hope they not gonna die often :)

**Comment by otpisani** [comment]
I can also confirm that my tx MGA-81563 burned, I wad doing some testing with gnuradio-companion and transmit with attached exteranl amp, but I didn't get even close to magic number of -5dbm. I also have couple of spare  MGA-81563, but can someone test suggested part like LVA-123+ or similar, did hackrf one operates or not, also  when you are using mayhem and transmit something @mautas with replaced MGA-81563, hackrf one operate like it should or not???

**Comment by LilaQ** [comment]
Why is this closed? Did anything ever come of this? Like, implementing any of the proposed solutions 5 years ago in 2018?

Tbh reading about the huge amount of issues with blown amps, I might just return my hackrf. I'm not keen on checking all the time if the inevitable has happened yet or not.

**Comment by bm16ton** [comment]
Almost 10 years ago I rwceived my hackrf. I am nnot a financially rich person, my hackrf was the most expensive thing I owned..I killed it first night, I didn't know about this limitation and was trying tto look at wifi. I just now have received new pre-amps to try and install (yikes tgats tiny) Sounds silly saying it out loud now, but truely, unbelievably depressing thing. Id see it on the shelf from time to time and feel tge pain all over again. It was so long ago my memorry if foggy but I thought I was no longer able to tx/rx on anything over like 2ghz, and those symptoms haven't been mentioned that I can see for the pre-amps. Now I'm terrified thers a different problem maybe..Good god its still the most expensive thing I own. Anyway I have seen sum very cheap protection circuits that can be added to antenna port, but I need to learn and research them unless a official device that does the trick exists and I can purchase from great scotts? I don't want to go thru that again :)

**Comment by otpisani** [comment]
This subject is also processed in more details here<https://github.com/greatscottgadgets/hackrf/issues/541> , and Clifford Heath  also made changes, you have option to buy he's changes, and some Chiness company made HackrRF with Clifford changes, or you can try to made changes by yourself. I can confirm that Clifford HackrRF card actually works for me 24/7 in TX mode, I don't use RX, I also have Chinesse clone from original Mossmann HackRF revision r7, and they suffer also from MGA-81563 disease, but must admit r7 last much longer for me (around 2 weeks) than previous hardware changes, after that you can't use additional gain of 14dB.
[https://opengraph.githubassets.com/9960241b23faf341d31f2bd359c2e1fab5a2fc8118e899511281a9fce51e8bfe/greatscottgadgets/hackrf/issues/541]<https://github.com/greatscottgadgets/hackrf/issues/541>
Antenna port needs better protection · Issue #541 · greatscottgadgets/hackrf<https://github.com/greatscottgadgets/hackrf/issues/541>
Steps to reproduce Expose the antenna to nearby 17kW airport radar (under 2km distance) while in receive mode Discover that the MMIC input amplifier is fried and receive sensitivity is greatly redu...
github.com

If you want to made changes by yourself, this is what you need to change on TX and RX side:

[cid:143c7c6a-9f91-42b2-8c7f-de06427ca59c]

If you want to buy new card with Clifford changes this is link<https://www.amazon.com/gp/product/B0BYSN6XZZ/ref=ppx_yo_dt_b_asin_title_o00_s00?ie=UTF8&psc=1>, but on the board need to be sign CKT08Mar2021

________________________________

**Comment by LilaQ** [comment]
I read the other thread, and it baffles me how this is just being ignored for 5 years basically. 
I don't want to buy chinese clones without any warranty, nor do I want to buy changes from a third-party only to ensure the basic functionality keeps existing (and btw you can NOT buy the changes off Clifford anymore, I asked), nor do I want to solder things on it, void my warranty and potentially destroy it like that.

The lack of interest of the creators to fix this issue easily convinced me to return the hackrf and wait for alternatives that don't destroy themselves.

**Comment by otpisani** [comment]
Actually you can buy it, I'm in rhe process right now to buy another one, inspired by yours tread, but on Ali;
  
Robin
  

  

  

  
  
  
  
  
>

**Comment by surpscare** [comment]
Gn, I have a question. My HackRF seems to be totally blind to anything above 2700 MHz. I can't see any spikes from my 5G router even sitting right on it, with any antenna attached. May it be caused by damage in some components like the I/Q converter or filter? I've before tried to use an attached phantom-powered antenna for reception, but it had a short circuit and I quickly noticed a burning smell by HackRF and turned it off. Everything seems to stay intact, and RX/TX features didn't suffer. Also as far as I remember, sensitivity in the 3-4-5-6G band never seemed to be great with my unit, but at that time I didn't have a 5G router to check it out. May this be caused by the older firmware or a hardware issue?
