### ISSUE TITLE
Cmake is unable to find FFTW on cygwin

### ISSUE THREAD

**Issue by Anjum9694** [greatscottgadgets/hackrf#977]
### Steps to reproduce
1.cd host/build
2.cmake ../ -G "Unix Makefiles" -DCMAKE_LEGACY_CYGWIN_WIN32=1 -DLIBUSB_INCLUDE_DIR=/usr/local/include/libusb-1.0/
3.

### Actual behaviour
I have installed fftw3 on cygwin setup but it's still failing

### Version information
**Operating system**: Windows 10 building on Cygwin

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
$ cmake ../ -G "Unix Makefiles" -DCMAKE_LEGACY_CYGWIN_WIN32=1 -DLIBUSB_INCLUDE_DIR=/usr/local/include/libusb-1.0/
CMake Deprecation Warning at CMakeLists.txt:3 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Defining WIN32 under Cygwin due to CMAKE_LEGACY_CYGWIN_WIN32
CMake Deprecation Warning at libhackrf/CMakeLists.txt:24 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Deprecation Warning at hackrf-tools/CMakeLists.txt:24 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


CMake Error at /usr/share/cmake-3.20.0/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find FFTW (missing: FFTW_LIBRARIES)
Call Stack (most recent call first):
  /usr/share/cmake-3.20.0/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindFFTW.cmake:28 (find_package_handle_standard_args)
  hackrf-tools/src/CMakeLists.txt:26 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/Anjum/hackrf-2021.03.1/host/build/CMakeFiles/CMakeOutput.log".
See also "/home/Anjum/hackrf-2021.03.1/host/build/CMakeFiles/CMakeError.log".


```

**Comment by straithe** [comment]
Good catch! Have you tried updating from source?

**Comment by Anjum9694** [comment]
Steps taken:

```
curl -L http://www.fftw.org/fftw-3.3.9.tar.gz | tar xz
./configure
make
make install
```

Still the hackrf cmake outputs Could NOT find FFTW (missing: FFTW_LIBRARIES)

**Comment by straithe** [comment]
Sorry, I meant to say, have you tried updating your HackRF firmware from the GitHub repository?

**Comment by Anjum9694** [comment]
I was able to update the firmware of my hackrf itself through linux, it was pretty easy. I'm trying to compile the source to use hackrf_tools executables on windows.

**Comment by Anjum9694** [comment]
SOLUTION:

After installing libusb devel packages from cygwin you won't need to mention its location as a flag, so

`cmake ../ -G "Unix Makefiles" -DCMAKE_LEGACY_CYGWIN_WIN32= -DFFTW_LIBRARY=/lib/`
copy the libusb.h file in usr\include\libusb-1.0 to usr\include\
make and make install should run smoothly.

**Comment by straithe** [comment]
Thank you for the update!
