### ISSUE TITLE
Signal lost until i change frequency

### ISSUE THREAD

**Issue by theorywrong** [greatscottgadgets/hackrf#979]
### Steps to reproduce
1.  Open a SDR program or even hackrf_sweep
2.  Try to got signal
3.  Nothing happen (~ of -60 / -70 dB)
4. Change frequency multiple time and signal is got for like 2 seconds

### Expected behaviour
Everything should work (Data is got everytime)

### Actual behaviour
Data is got only when i change frequency multiple time
Here a video: https://youtu.be/xz94_KKOd90

### Version information
**Operating system**:
Windows 10 (20H2)

**hackrf_info output:**
hackrf_info version: git-7047252
libhackrf version: git-7047252 (0.6)
Found HackRF
Index: 0
Serial number: 000000000000000026b468dc3621288f
Board ID Number: 2 (HackRF One)
Firmware Version: 2021.03.1 (API:1.04)
Part ID Number: 0xa000cb3c 0x005d4359

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
SDR# 1.0.0.1830
```

Insert any commandline or build output here
```

**Comment by mossmann** [comment]
This looks like a hardware failure (an unusual one!). Please a replacement from your reseller.
