### ISSUE TITLE
HackRF One Transmission Tones

### ISSUE THREAD

**Issue by watsonlg** [greatscottgadgets/hackrf#980]
Hello,

I was interfacing with the HackRF via command line input. When transmitting at high frequencies, for example 6 GHz, a spectrum analyzer showed the two tones used to generate the 6 GHz frequency. I believe these are the result of the IF and LO stages.

1. It seems as the result of the architecture, the HackRF One is not capable of a creating a pure tone 6 GHz signal. Is this correct?
2. Does the HackRF One have any internal filtering on the Tx end to attenuate the tones used to generate the high frequency signal?

Thank you!

**Comment by straithe** [comment]
Yes, you are correct. The HackRF One is not capable of creating a pure 6 GHz signal. 

HackRF does have some internal filtering but maybe not as much as you are looking for. You may need to add external filtering for some applications.

**Comment by watsonlg** [comment]
Thank you straithe, 

Do you know if the internal filtering is enabled by default or does the filter need to be enabled?

**Comment by straithe** [comment]
Internal filtering is always enabled.

**Comment by straithe** [comment]
Do you have any other related questions, or may I close this issue now?
