### ISSUE TITLE
Ship the udev rules upstream

### ISSUE THREAD

**Issue by AsciiWolf** [greatscottgadgets/hackrf#983]
Please, consider submitting the [udev rules](https://github.com/greatscottgadgets/hackrf/blob/master/host/libhackrf/53-hackrf.rules) to upstream (systemd). Here is an example how to do it: https://github.com/systemd/systemd/pull/20561

Without this, it is [not possible](https://github.com/flatpak/xdg-desktop-portal/issues/227#issuecomment-946760482) to use HackRF SDR devices in Flatpak and other special configurations where it is not possible to install the HackRF libs/udev rules system-wide.

**Comment by straithe** [comment]
Thank you for the suggestion. I think it is a great idea. I will try to get to this as soon as I can, but my schedule is full for tasks until at least December.

**Comment by straithe** [comment]
After deliberating our team has decided not to submit the udev rules upstream to systemd. Thanks.

**Comment by AsciiWolf** [comment]
https://github.com/systemd/systemd/issues/37019

**Comment by AsciiWolf** [comment]
If you ever re-consider this, bladeRF was already added into systemd hwdb and can be used as an example of how the changes should look like:

https://github.com/systemd/systemd/blob/main/hwdb.d/70-software-radio.hwdb

**Comment by AsciiWolf** [comment]
@straithe Are we allowed to add these rules to systemd or do you want them to stay downstream? Thanks!

**Comment by AsciiWolf** [comment]
Note that no action will be required from you or your team. We will add the rules and handle any possible problems.

The only thing we ask of you is to either allow or deny us doing it. :-)

**Comment by AsciiWolf** [comment]
Let's do it the other way around: The HackRF rules will be added to the upstream hwdb (where they should be) by us. If you do not agree or find this potentially problematic, please let us know and the rules will be removed. But please provide a valid reason. Thanks!

Note that the upstream udev rules should not conflict with the original hackrf rules. In fact, you should continue to ship your rules (without any changes needed) since they contain additional things (like the _SYMLINK_ rule) that the upstream hwdb does not support.

**Comment by AsciiWolf** [comment]
https://github.com/systemd/systemd/pull/38890
