### ISSUE TITLE
Rx Tx problem with amp/ signal is gone

### ISSUE THREAD

**Issue by Mopar44084** [greatscottgadgets/hackrf#999]
### Steps to reproducce
1. Use hackrf with sdrsharp or other app
2. Tune to frequency or transmit
3. Turn amp to 1

### Expected behaviour
Tell us what you expect should happen
Amplifies signal

### Actual behaviour
Tell us what happens instead
Signal is gone or will not transmit with amp on
Vga/LNA is weak without amp also

### Version information
**Operating system**:
HamPi os RPI 3
Skywave Linux - Ubuntu 16.04 - laptop
Mayhem 1.4.1 - original portapack h1

**hackrf_info output:**

If you are reporting a problem that involves third party software 
(GNU Radio, Gqrx, etc), please report the version here.

### Output
```
Insert any commandline or build output here
```

**Comment by straithe** [comment]
Can you show me what your waterfall looks like before and after you enable the amp?

**Comment by Mopar44084** [comment]
The first 2 pictures are from mayhem 1.4.1 
Second 2 pictures and video is from cubicsdr on skywave Linux. This is a local radio station, it used to have a lot more red in the waterfall, now I have to crank up LNA and VGA to even get a signal
![SCR_0000](https://user-images.githubusercontent.com/86167080/143957899-2f2ae892-0148-4633-917e-cc20d64dc528.PNG)
![SCR_0000](https://user-images.githubusercontent.com/86167080/143957932-21a529a0-601e-41df-baaf-b76439c19f17.PNG)
![Screenshot at 2021-11-29 16-04-38](https://user-images.githubusercontent.com/86167080/143957969-211a6e67-843c-4587-9ce1-f7e5f35bfb65.png)
![Screenshot at 2021-11-29 16-04-47](https://user-images.githubusercontent.com/86167080/143957983-be7afe77-1eda-4e07-ac11-342cfb7d9108.png)

**Comment by Mopar44084** [comment]
The first 2 pictures are from mayhem 1.4.1 
Second 2 pictures is from CubicSDR on Skywave Linux. This is a local radio station, it used to have a lot more red in the waterfall, now I have to crank up LNA and VGA to even get a signal
![SCR_0000](https://user-images.githubusercontent.com/86167080/143958486-e4a1a51c-a0a5-46d4-a1ab-805bc46812fb.PNG)
![SCR_0001](https://user-images.githubusercontent.com/86167080/143958494-7d57b526-57de-46f7-b404-d4356bcca2ef.PNG)
![Screenshot at 2021-11-29 16-04-38](https://user-images.githubusercontent.com/86167080/143958509-28e2f165-255e-42e0-80d4-890f6d4287be.png)
![Screenshot at 2021-11-29 16-04-47](https://user-images.githubusercontent.com/86167080/143958519-be633d68-1a09-421d-a5f6-261eef46ba26.png)

**Comment by Mopar44084** [comment]
This is using CubicSDR on Skywave Linux
https://user-images.githubusercontent.com/86167080/143959091-b0dd1c4a-2c76-4619-b6da-89c6c8cb1fd4.mp4

**Comment by straithe** [comment]
Thanks for the extra information. I'm a bit limited in how I can help with your current setup as I don't know much if anything about CubicSDR, Skywave Linux, or Mayhem. To clarify, it seems that you primarily want help assessing if the HackRF hardware is ok. Is that correct?

**Comment by Mopar44084** [comment]
I believe there may be a hardware problem, when amp is selected it cuts the signal and overall I have noticed a reduction in signal. When I tx in amp mode it also cuts the signal.

**Comment by straithe** [comment]
That's an interesting idea! Can you first post a picture of your HackRF (front and back) here?

**Comment by Mopar44084** [comment]
![IMG_20211204_070744029_HDR](https://user-images.githubusercontent.com/86167080/144712619-b664adee-9d16-4431-8a49-fe73670a953e.jpg)
#
![IMG_20211204_070420961_HDR](https://user-images.githubusercontent.com/86167080/144712626-11d35595-27c8-4386-83e0-d7334a3f94cd.jpg)
![Uploading IMG_20211204_070435468_HDR.jpg…]()

**Comment by Mopar44084** [comment]
![IMG_20211204_070744029_HDR](https://user-images.githubusercontent.com/86167080/144712704-5aab296e-79d5-4d82-be99-ab1f20828a0a.jpg)
![IMG_20211204_070420961_HDR](https://user-images.githubusercontent.com/86167080/144712706-83d1b2cc-05af-49f6-99a9-170191d8ad66.jpg)
![Uploading IMG_20211204_070435468_HDR.jpg…]()

**Comment by straithe** [comment]
If you tried to send a picture of the back of the HackRF it didn't come through. Could you post again?

**Comment by Mopar44084** [comment]
![Uploading IMG_20211204_070435468_HDR.jpg…]()

**Comment by Mopar44084** [comment]
Here is the back, I don't know why it wouldn't send?
![Uploading IMG_20211204_070435468_HDR.jpg…]()

**Comment by gozu42** [comment]
wth github? 
i can see @Mopar44084 trying to repost the backside image on discord #github-updates ... 
... but i cant see the posts here? 
not even if i go to the specific URL in the notifications, and it doesnt seem like a client-side caching issue either.

**Comment by Mopar44084** [comment]
I am not sure why it didn't send, sorry!
![Hackrf one](https://user-images.githubusercontent.com/86167080/144951388-26d2b2f5-eefc-46a6-8c8f-2bfcf2fe9d5f.jpg)

**Comment by straithe** [comment]
I don't see any obvious faults with the board, but it does sound like you've encountered a hardware problem, so I suggest contacting the reseller you purchased the board from. As long as you've operated the board within the specifications in our documentation (https://hackrf.readthedocs.io/en/latest/hackrf_one.html#transmit-power) they should be able to help you out!

**Comment by Mopar44084** [comment]
Thanks! Is there anything I need to tell them? I bought it from nooelect.

**Comment by straithe** [comment]
Nothing specific. Going through their customer support should be sufficient.

**Comment by Mopar44084** [comment]
I sent Nooelec 2 mails and left a message and they don't seem to respond, anything else I can do?

**Comment by straithe** [comment]
Can you reach out to the info@greatscottgadgets.com and include a link to this ticket?

**Comment by Mopar44084** [comment]
I just sent one out, along with my receipt from nooelec.

Thank you!

**Comment by Mopar44084** [comment]
Is there a way you can check into my RMA info at nooelec?
I got an email in February 23 that it would take 4-12 weeks.

Thanks a lot!

**Comment by straithe** [comment]
You're still within that 12 week period so please check back once that 12 weeks has elapsed.
